### ISSUE TITLE
echo has("python3")  returns 0

### ISSUE THREAD

**Issue by gerroon** [vim/vim-win32-installer#100]
Hi

I am trying to find a Vim compiled with Python37, you claim it is compiled with python3, but the flag tells me the opposite. Am I missing something here? I tried both the x64 and x86 versions

**Comment by k-takata** [comment]
Does `python37.dll` exist in the $PATH?
What does `:!where python37.dll` show? If it isn't found, add the path of python37.dll to the PATH environment variable.
Or you can try setting the `'pythonthreedll'` option.

**Comment by gerroon** [comment]
HI

I put all the Python embed files into the Vim folder (after your commend on python37.ddl)  and now it works, thanks

**Comment by jinyouq** [comment]
> 

Hi gerroon, I met the same issue. Could you please help provide the detailed solution, like WHICH files you put to WHICH vim  folder.
