### ISSUE TITLE
Broken link to 64 bit build

### ISSUE THREAD

**Issue by frederik-h** [vim/vim-win32-installer#101]
The link to the 64 bit release for Windows at the [vim website's download page](https://www.vim.org/download.php) is broken. (I am not sure if this is the right place to report this; probably it is!?)

**Comment by chrisbra** [comment]
Ah that probably needs to be either https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0001 or perhaps better: https://github.com/vim/vim-win32-installer/releases/latest

@brammool can you correct the link on the vim.org page please?

**Comment by k-takata** [comment]
I confirm that the vim.org page has been updated. Closing.
