### ISSUE TITLE
Cannot Set Font Properly in mui2.exe

### ISSUE THREAD

**Issue by Neur1n** [vim/vim-win32-installer#102]
Hello, I'm not trying to complain anything but to mention it if it is not a known issue. That is, it seems that I could not set `guifont` properly if there is a whitespace in between of the font name, like `set guifont=foo\ bar:h10`. But setting like `set guifont=Consolas:h10` works fine. Also, using `set guifont=*` that invokes a font selector makes the font works properly. But then `:set guifont` echos something like `guifont=foo_bar:h10:...` which even I set the font by following the same full string it didn't work. Thanks.

**Comment by Neur1n** [comment]
After I tried out several nightly build and switch back the other day, it worked again. I don't know why. 🤨 Sorry.

**Comment by k-takata** [comment]
I'm closing this for now. Feel free to reopen if it is reproduced.

**Comment by Neur1n** [comment]
Sure, thanks for the patience.
