### ISSUE TITLE
Remove The Capation In Windows

### ISSUE THREAD

**Issue by gVimer** [vim/vim-win32-installer#105]
I Want To Remove The Capation,I Try Many Times To modify The Source Code and Rebuild It,But Failed.Can You Help Me? Could You Consider Add A Option To Gvim Like Scroll Bar? Like This: set go-=C (Remove The Capation)

**Comment by k-takata** [comment]
To just remove the caption, you can use this:

```diff
--- a/src/gui_w32.c
+++ b/src/gui_w32.c
@@ -5510,7 +5510,7 @@ gui_mch_init(void)
 	 * titlebar, it will be reparented below. */
 	s_hwnd = CreateWindow(
 		szVimWndClass, "Vim MSWindows GUI",
-		(win_socket_id == 0 ? WS_OVERLAPPEDWINDOW : WS_POPUP)
+		(win_socket_id == 0 ? WS_POPUPWINDOW : WS_POPUP)
 					  | WS_CLIPSIBLINGS | WS_CLIPCHILDREN,
 		gui_win_x == -1 ? CW_USEDEFAULT : gui_win_x,
 		gui_win_y == -1 ? CW_USEDEFAULT : gui_win_y,
```

However you cannot change the window position and size my mouse.

**Comment by gVimer** [comment]
Thanks For You Replay ! In Fact,T Have Alerady Do Many Trys,But I Meet A Question When Create A New Tab.Please See The Picture:
Normal:[https://imgchr.com/i/FNIbLT](url)
After Create A new Tab,The Vim WIndows's Size Changed :[https://imgchr.com/i/FNIHyV](url)

**Comment by gVimer** [comment]
> You might be able to use @koron's caption switch patch:
> https://github.com/koron/vim-kaoriya-patches/blob/master/master/2004-caption_switch.diff

OK .I Will Try To Do

**Comment by gVimer** [comment]
I Solved The Problem By Other Way
