### ISSUE TITLE
Optional vim path in the PATH environment variable

### ISSUE THREAD

**Issue by duianto** [vim/vim-win32-installer#110]
### Feature request

To make it possible to use `vim` from the `cmd` and `powershell` prompts.

Maybe the installer could have an option to add the path `C:\Program Files\Vim\vim81` (to `gvim.exe`) to the `PATH` environment variable.

**Comment by k-takata** [comment]
There is an option to create `vim.bat` and `gvim.bat` in a directory in `PATH` so that you can use `vim` from `cmd`.
Normally, this can be the alternative for that.

**Comment by duianto** [comment]
Thanks. 

I should have done a more global search, not just in this repo, now I found an answer on SO:

>When you install gVim:
Please make sure [✓] Create .bat files for command line use is checked.
It'll create several .bat files in C:\Windows\:
>
>C:\>cd %windir%
C:\WINDOWS>dir /b *.bat
evim.bat
gview.bat
gvim.bat
gvimdiff.bat
view.bat
vim.bat
vimdiff.bat
vimtutor.bat
>
>Notice that: C:\WINDOWS is already in the PATH environment variable.
When you type vim in command line, C:\WINDOWS\vim.bat will be launched.
If you leave the checkbox mentioned above unchecked, you need to modify PATH manually.

source: How do you run Vim in Windows? https://stackoverflow.com/a/10051146

But I guess this will be searchable from now on as well 😄

**Comment by jazzdelightsme** [comment]
How do you activate the "create .bat files" option when running the installer silently? E.g. from winget?

(Also, I cannot find any documentation about the installer's command line options to see if I could figure it out myself--are they documented somewhere?)
