### ISSUE TITLE
Gvim crash when executing ":py3 print(sys.version)"

### ISSUE THREAD

**Issue by joeyling** [vim/vim-win32-installer#111]
If I execute other python-support plugin Ex command in Gvim, like `:Leaderf`, it crashed too.
Please check the screenshot below.
![image](https://user-images.githubusercontent.com/46703188/54071589-8e8ca900-42a9-11e9-9e21-d4bd880e58af.png)

Gvim version:
![image](https://user-images.githubusercontent.com/46703188/54071613-eaefc880-42a9-11e9-80c2-0a5adf923c2f.png)

**Comment by chrisbra** [comment]
what python version are you using? Does the architecture match that of Vim?

**Comment by miemiekurisu** [comment]
same problem, python 3.7.3's python3.dll will make vim crash

**Comment by chrisbra** [comment]
closing then.
