### ISSUE TITLE
Remove experimental/recommended label

### ISSUE THREAD

**Issue by chrisbra** [vim/vim-win32-installer#112]
Can we remove the experimental/recommended labels from the releases page for the MUI installer? I think it is safe to assume now, that the 64bit installer works okay and there haven't been any changes for a while.

ping @k-takata

**Comment by k-takata** [comment]
Ah, I think it's okay.
(Bram might still recommend 32-bit version than 64-bit version, though. He doesn't provide 64-bit installer yet.)

**Comment by chrisbra** [comment]
wasn't the experimental mainly because of the new installer MUI vs. the old one NSIS based installer?

**Comment by k-takata** [comment]
Yes, that was the main reason, but the second reason was as I wrote above.
