### ISSUE TITLE
x86 binaries are not provided from v8.1.1045

### ISSUE THREAD

**Issue by rhysd** [vim/vim-win32-installer#114]
Binaries for x86 are not provided from v8.1.1045

https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1045
https://github.com/vim/vim-win32-installer/releases/tag/v8.1.1048

I'm not sure but auto build may be broken.

**Comment by chrisbra** [comment]
The reason are flaky tests. See also https://groups.google.com/forum/#!topic/vim_dev/yXcq-DZe39k
Let me retrigger the build.

**Comment by rhysd** [comment]
I got it. Thanks for your support.
