### ISSUE TITLE
Please DO NOT delete $VIM/_vimrc by default

### ISSUE THREAD

**Issue by ijliym** [vim/vim-win32-installer#115]
Hello! Can you set up to re-install GVim without deleting the `$VIM/_vimrc` file by
default? It is very inconvenient.

As l known, the `gvim81.exe` download from
`https://www.vim.org/download.php#pc` does not delete $VIM/_vimrc by default.

Thanks very much!

**Comment by k-takata** [comment]
Could you tell us more detail about your use case?
`$VIM/_vimrc` is normally created under `C:\Program Files (x86)`. It means that `$VIM/_vimrc` is readonly. If you want to edit it, you need an administrator privilege and need to use UAC.
Do you install Vim somewhere else and/or edit `$VIM/_vimrc` by yourself?

**Comment by k-takata** [comment]
If you don't want to delete `$VIM/_vimrc`, you should uncheck "Remove the Vim root directory".
`gvim81.exe` doesn't have the checkbox. Instead it shows a message box "Would you like to remove $VIM? It contains your Vim configuration files!" with default "Yes". If you select "Yes", `$VIM/_vimrc` will be also deleted. So, the default is not changed from `gvim81.exe`.

**Comment by ijliym** [comment]
Yes, my Vim installation dir is `D:\ProgramFiles\Vim`, and use `D:\ProgramFiles\Vim\_vimrc` as the default initialization file. So I do not want the `gvim_8.1.***_x64.exe` delete `D:\ProgramFiles\Vim\_vimrc` when I re-install (that is `Upgrade`) the Vim by default.

**Comment by ijliym** [comment]
Thank you very much!

**Comment by k-takata** [comment]
Fixed by [8.1.1159](https://github.com/vim/vim/commit/a8d22e3a40483cd1fa9c6e45dcf383f49f16833a). Closing.
