### ISSUE TITLE
Windows x86 build is broken

### ISSUE THREAD

**Issue by skywind3000** [vim/vim-win32-installer#133]
Can't use the latest version on win32

**Comment by chrisbra** [comment]
what do you mean? Please be more specific. Do you get an error message? What Windows version?

**Comment by k-takata** [comment]
I think he is talking about the build failure:
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/09l4208qbrmaif4f#L6891

**Comment by chrisbra** [comment]
ah that was what I suspected, but the problem description was a bit vague.

Yeah, I noticed the build problem. I suggest a patch on the memory test: https://groups.google.com/forum/#!topic/vim_dev/GvqxWQ8f-Ps

Until this is fixed, I suggest using the x64 build.

**Comment by skywind3000** [comment]
Yes, no download URL for x86 build.

I am using a 32bits python for work, upgrading gvim to 64bits or install a separated python 64 will introduce problems.

So I have to wait for the next availble x86 build.

**Comment by k-takata** [comment]
Fixed by [8.1.1435](https://github.com/vim/vim/commit/5d508dd39e810d446f29dfd4f4e745b802875001).

**Comment by skywind3000** [comment]
thanks
