### ISSUE TITLE
System error on starting gvim

### ISSUE THREAD

**Issue by eevan78** [vim/vim-win32-installer#134]
I installed a 32-bit signed installer of 8.1.1568 on Win7 x64 and when I start the gvim, the following pops up.

![Error](https://user-images.githubusercontent.com/27575106/59736814-2d8f4c80-926c-11e9-83da-84270b48dd67.jpg)

When I click OK, the program starts, but I have noticed, for example, that it's not possible to change the messages language. English is shown regardless of the value of $LANG, or after a command like ":lang mes de" for example.

Before I had the version 1324 installed, and that one was starting and working normally.

**Comment by k-takata** [comment]
Hmm, it seems that `libgcc_s_sjlj-1.dll` which comes with gettext 0.20.1 depends on `libwinpthread-1.dll`.
It might be better to revert #121 until next version of gettext-iconv-windows is released.
