### ISSUE TITLE
a bug with "--remote-tab-silent" and filename "(a).txt"

### ISSUE THREAD

**Issue by hyaray** [vim/vim-win32-installer#136]
I test gvim.exe by command line on win7 x64.
1. `gvim.exe "c:\Users\Administrator\Desktop\(a).txt"`
worked

2. `gvim.exe --remote-tab-silent "c:\Users\Administrator\Desktop\(a).txt"`
add `"--remote-tab-silent"` --->not worked
edit file is "C:\Users\Administrator\Desktop(a).txt"
the problem is filename start with '("

3. `gvim.exe --remote-tab-silent "c:\Users\Administrator\Desktop\\(a).txt"`
add a '\\', worked again

so, is there a problem with '--remote-tab-silent'? thanks a lot!!!

**Comment by chrisbra** [comment]
please report vim issues directly at https://github.com/vim/vim
