### ISSUE TITLE
Strange bar appears when maximized

### ISSUE THREAD

**Issue by grinning2015** [vim/vim-win32-installer#137]
Strange bar appears here when maximized,
between command area and system task bar.
![test](https://user-images.githubusercontent.com/51905461/61178144-50b5dd80-a619-11e9-956d-a1179681132e.png)

**Comment by chrisbra** [comment]
I believe this is caused by the fact, that not a whole cell can be drawn on the bottom line, so you just see a border, have a look at `:h gtk-css`, I believe you can style it.

**Comment by grinning2015** [comment]
> I believe this is caused by the fact, that not a whole cell can be drawn on the bottom line, so you just see a border, have a look at `:h gtk-css`, I believe you can style it.

thanks for ur reply.
but where can i find the gtk.css file?
it is not found in vim81 directory.
