### ISSUE TITLE
vim-fugitive fail to Gpush starting from version 8.1.1661 on Windows 10

### ISSUE THREAD

**Issue by habamax** [vim/vim-win32-installer#138]
Hi, I have just found that vim-fugitive fails to Gpush my commits.

I have created an issue for https://github.com/tpope/vim-fugitive/issues/1289 but just in case open another one here.

Basically starting from 8.1.1661 I get error whenever I try to `:Gpush`:
![image](https://user-images.githubusercontent.com/234774/61242089-83f98900-a74d-11e9-85c4-b594b0665d1c.png)

It works in 8.1.1657

**Comment by habamax** [comment]
The original issue on vim-fugitive was fixed in a workaround way to prevent escaping for windows paths. While it works for paths without spaces it will defntly not work for paths with spaces.

I have tried to look on what has changed since 8.1.1657 to 8.1.1661 but couldn't find anything related to it. :(

**Comment by chrisbra** [comment]
would be interesting to see the actual command, that was trying to be executed. Anyway, this is an issue, that should rather be reported at the vim/vim repository, with clear steps to reproduce.

> I have tried to look on what has changed since 8.1.1657 to 8.1.1661 but couldn't find anything related to it. :(

Yeah, I agree, https://github.com/vim/vim/compare/v8.1.1657...v8.1.1661  doesn't contain anything related to executing system commands :(

**Comment by habamax** [comment]
Well the actual command that fails is probably `:Dispatch git -C "C:/Users/maksim.kim/docs" push` that fails.

Without escaping (workaround added by @tpope) `:Dispatch git -C C:/Users/maksim.kim/docs push` -- this one works.

I will try to add it to vim issues.

**Comment by chrisbra** [comment]
And what does `:Dispatch` do?

**Comment by chrisbra** [comment]
closing for vim/vim#4682

**Comment by habamax** [comment]
And what does :Dispatch do?

It is another plugin of @tpope vim-dispatch that is used by vim-fugitive under the hood (as far as I understand)

```
:Dispatch[!] [options] {program} [arguments]
                        Find a compiler plugin that sets 'makeprg' to
                        {program} and use its 'errorformat' to dispatch a
                        |:Make| for the given {program} and [arguments].  If
                        no compiler plugin is found, the generic format
                        %+I%.%# is used.
                        ...

:Make [arguments]       Using the current |:compiler| settings, dispatch a
                        build in the foreground.  Adapter strategies vary, but
                        the goal is visibility without stealing focus.  When
                        the build is complete, load the results into the
                        |quickfix| list and call |:cwindow|.  This command is
                        preferred for shorter tasks like "build this file."


```
