### ISSUE TITLE
I installed VIM with 8.1 installer, but at the end version 7.4 got installed (and not 8.1)

### ISSUE THREAD

**Issue by bjce** [vim/vim-win32-installer#142]
Hello

I'm trying to install VIM 8.1 on my PC for Windows 10 at work (on which there has not been VIM installed to my knowledge). `https://www.vim.org/download.php#pc`. I successfully installed VIM (with many times the version 8.1 appearing during setup) but when I type `:version` in the freshly installed vim it tells me that I have version `7.4`: (without python3 for example):

P.S.: The same happened when I ran the `gvim_8.1.1839_x86.exe` from [the freshest install version](https://github.com/vim/vim-win32-installer/releases)

```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:33:40)
MS-Windows 32-bit console version
Compiled by mool@tororo
Big version without GUI.  Features included (+) or not (-):
+arabic          +cscope          +float           -lua             -profile         +tag_binary      +vreplace
+autocmd         +cursorbind      +folding         +menu            -python          +tag_old_static  +wildignore
-balloon_eval    +cursorshape     -footer          +mksession       -python3         -tag_any_white   +wildmenu
-browse          +dialog_con      +gettext/dyn     +modify_fname    +quickfix        -tcl             +windows
++builtin_terms  +diff            -hangul_input    +mouse           +reltime         -tgetent         +writebackup
+byte_offset     +digraphs        +iconv/dyn       -mouseshape      +rightleft       -termresponse    -xfontset
+cindent         -dnd             +insert_expand   +multi_byte      -ruby            +textobjects     -xim
+clientserver    -ebcdic          +jumplist        +multi_lang      +scrollbind      +title           -xterm_save
+clipboard       +emacs_tags      +keymap          -mzscheme        +signs           -toolbar         -xpm_w32
+cmdline_compl   +eval            +langmap         -netbeans_intg   +smartindent     +user_commands
+cmdline_hist    +ex_extra        +libcall         +path_extra      -sniff           +vertsplit
+cmdline_info    +extra_search    +linebreak       -perl            +startuptime     +virtualedit
+comments        +farsi           +lispindent      +persistent_undo +statusline      +visual
+conceal         +file_in_path    +listcmds        -postscript      -sun_workshop    +visualextra
+cryptv          +find_in_path    +localmap        +printer         +syntax          +viminfo
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32   -DFEAT_CSCOPE       -DWINVER=0x0400 -D_WIN32_WINNT=
0x0400  /Fo.\ObjCi386/ /Ox /GL -DNDEBUG  /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_BIG /Fd.\ObjCi386/ /Zi
Linking: link /RELEASE /nologo /subsystem:console /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.
lib  comdlg32.lib ole32.lib uuid.lib /machine:i386 /nodefaultlib  libcmt.lib   user32.lib             /PDB:vim.pdb -debu
g
```
How can I install version 8.1??

**Comment by chrisbra** [comment]
Use the https://github.com/vim/vim-win32-installer/releases to download and install the latest releases.

**Comment by bjce** [comment]
thank you for your answer @chrisbra. That's what I already did (in the link "freshest install version" in my question). But unfortunatelly the same problem happened

**Comment by chrisbra** [comment]
Check your path, it looks like you have an older vim version laying around and that is used.

**Comment by chrisbra** [comment]
The version from here will never have `Compiled by mool@tororo`, that is from the official Vim installation from https://www.vim.org

**Comment by bjce** [comment]
thanks a lot @chrisbra. As I'm not used to pc (I use it for my work but normaly i use MacOS), How do I check the path? In Windows 10, I went to control panel > all control panel items > system > advanced system settings > environment variables > path but I didn't find any path for vim there. Do you have any idea of what I should do? sorry for this other question, but that would really help

**Comment by chrisbra** [comment]
Well, how did you startup vim? In a cmd line window, I believe you can also check `where vim` or `where gvim` to find out which gvim will be called. Alternatively do `path` and check the path setting for other vim installations. Or from vim you can check `:echo v:progpath` (however that might not exist on vim 7.4).

**Comment by bjce** [comment]
Many thanks again @chrisbra 

So I did the following command from the power Shell but literally Nothing happened: 
```
where vim
```

```
where gvim
```

I also tried the command: 

````
 $env:path
```
and got a long list of applications, among those
```
C:\Program Files (x86)\Vim\vim81;
```
but no vim 7.4!

from Vim i tried: 


```
:echo v:progpath1
```

but I got:

```
E121: Undefined variable: v:progpath
E15: Invalid expression: **v:progpath**
```

**Comment by chrisbra** [comment]
okay, remove the vim81 installation. Then start vim again (it should start the vim7.4 version again). Open Task manager, go to details, right click on a column and add the column cmdline (or whatever it is called in english) and look for the line gvim.exe and check the command line. That should tell you where the old installation is.

**Comment by bjce** [comment]
Ok @chrisbra, I finally found the path. It was under a `Gow` installation that i installed yesterday. I removed it, reinstalled vim 8.1 and added to the path and it worked. Many many thanks for your patient and your help
