### ISSUE TITLE
Colorscheme doesn't load from _vimrc; colorschemes can't be selected

### ISSUE THREAD

**Issue by AzureRaptor** [vim/vim-win32-installer#143]
When I start vim (installed from gvim_8.1.1866_x64.exe; Win 10, 1903 18362.295, _fresh clean_ vim install aside from slight customizations to _vimrc i.e. loading a colorscheme) I get the following error:

![Startup error dialog](https://i.imgur.com/Rjyk7mO.png)

Also, the :colorscheme command can't find _any_ installed colorschemes, including the ones in C:\Program Files\Vim\vim81\colors .  Am I doing something wrong?  Is this expected behavior?

(btw, I have no idea about the "line 166: error dialog is; the _only_ files I've customized are my _vimrc and placing the dw_green_2.vim colorscheme file in the abovementioned directory).

**Comment by chrisbra** [comment]
so where did you place the colorscheme?

**Comment by AzureRaptor** [comment]
Like I said, in C:\Program Files\Vim\vim81\colors .  I also tried my home directory, and C:\Program Files\Vim\vimfiles\colors .  No dice.

But, like I said, it's more than just my own file it's not recognizing.  It's not showing _any_ of the schemes in vim81\colors .

**Comment by chrisbra** [comment]
Check your $VIMRUNTIME environment variable and your `rtp` setting. Also show the output of `:echo globpath(&rtp, "colors/*.vim")`

Note, it is very unlikely, that this is actually a bug here, we would have gotten much more reports at the vim repository. It is more likely, this is a configuration issue and the vim_use mailinglist or vi.stackexchange.com are more appropriate forums for figuring this out. We cannot provide individual help here.

**Comment by AzureRaptor** [comment]
Well, I've figured it out, and this is a bit embarrassing.  There was an error in my _vimrc - it was made when I was still using the 32-bit version, and the runtime path had all the paths with ...(x86) in them, which obviously the 64-bit vim doesn't use.  Took me a while to catch that, but all was right with the world when I did.

I'm going to leave this here for the benefit of anyone else who encounters this trouble - if you fire up vim64, and you once had a vim32 installation, and it looks like this:

![image](https://user-images.githubusercontent.com/24552089/63242790-86f10900-c226-11e9-9dea-954670d790f9.png)

(default colors, odd subset menus, builtin commands such as colorscheme cannot find normal builtin files)

then you may have an issue with your $runtimepath .  I hope hope someone finds this helpful.
@chrisbra , thank you, and sorry to have taken up your time with this mess.

**Comment by AzureRaptor** [comment]
You must've been typing that up while I was in the process of my own answer.  I even tried to close it when I finished.  😆 Thanks again.
