### ISSUE TITLE
suggest: filetype.vim add 'snippets'

### ISSUE THREAD

**Issue by hyaray** [vim/vim-win32-installer#144]
add text at 1551 line of $Vim/filetype.vim
```
" snippets
au BufNewFile,BufRead *.snippets		setf snippets
```

**Comment by chrisbra** [comment]
this should go to the vim/vim upstream repository instead. However, what good would that rule do, considering that there isn't a snippets filetype plugin?

**Comment by hyaray** [comment]
I installed 'SirVer/UltiSnips',
Edit '*.snippets' file, syntax lighting not work, 
and show errer below:
has error on 'ultisnips\syntax\snippets.vim',
E484: can't open file 'ultisnips\syntax\sh.vim'
and there isn't a 'sh.vim' file at all.

maybe I need to learn filetype and syntax loading order. I'm disacquaintance on this.

**Comment by chrisbra** [comment]
that is most likely a utilsnip error (and you should reported it there).
