### ISSUE TITLE
Unable to install on Windows 10

### ISSUE THREAD

**Issue by uberhacker** [vim/vim-win32-installer#146]
I receive `The parameter is incorrect.` after attempting to execute `gvim_8.1.2044_x64.exe` on Windows 10 with all the latest updates.

**Comment by chrisbra** [comment]
this is not much information. I have no clue how to fix this one. Is there anything special on your system?

**Comment by uberhacker** [comment]
Yes, it happens during install.  No files actually get added to the filesystem.  Do you think the new version is worth a shot?  I know exactly what you mean about anti-virus software.  It tends to prevent you from doing anything useful on your PC. LoL

**Comment by uberhacker** [comment]
Hey @chrisbra: I tried the latest signed executable release and Panda Dome "neutralized" it.  I was able to install from the zip, however.  Looks like Sophos is not the only anti-vim (err, virus). :)
