### ISSUE TITLE
set encoding=utf-8 affects the value of $HOME

### ISSUE THREAD

**Issue by CaseZheng** [vim/vim-win32-installer#152]
set encoding=utf-8 will cause the value of $HOME to be wrong
set encoding=utf-8 before $HOME为 C:\Users\casezheng\
After set encoding=utf-8 $HOME is C:C:\Users\casezheng\

echo $HOME    C:\User\casezheng
set encoding=utf-8
echo $HOME    C:C:\User\casezheng
![图片](https://user-images.githubusercontent.com/17766535/66693542-8c297c00-ecdc-11e9-872f-48e520a1ec0c.png)

**Comment by chrisbra** [comment]
please open a new issue at the vim/vim repository about this. Thanks!
