### ISSUE TITLE
vim add acl file rule on samba file

### ISSUE THREAD

**Issue by BoysHands** [vim/vim-win32-installer#158]
hi,

I am using gvim as my default editor on my windows. Also I have a remote linux server with samba server on. So, I can edit file on linux server with my local gvim. 

When I edit and save files in samba directory，gvim will add  a acl rule on the file automatically, which make the file executable. I run command 'getfacl xxx' on the linux server, and a acl rule has been add to this file. I try to edit the same file with my local VSCode and sublime, they don't have such problem. 

So, I just wanna how to solve this problem with my gvim.

**Comment by chrisbra** [comment]
wrong repo. Please create your issue at vim/vim

**Comment by k-takata** [comment]
How about do `set nowritebackup`?
Anyway, wrong repo.

**Comment by BoysHands** [comment]
> 
> 
> How about do `set nowritebackup`?
> Anyway, wrong repo.

thanks，it doesn't work. i will create this issue at vim/vim.
