### ISSUE TITLE
Windows GVim 8.2 64bit "gx" executes "curl" downloading rather than open a browser under the url

### ISSUE THREAD

**Issue by heraldia** [vim/vim-win32-installer#161]
Windows 10 GVim 8.1 64bit "gx" executes "curl" to open a browser under the url;
But Windows 10 GVim 8.2 64bit "gx" executes "curl" downloading rather than open a browser under the url.

**Comment by k-takata** [comment]
It seems that it is the same as https://github.com/vim/vim/issues/4738.

**Comment by chrisbra** [comment]
closing for being a duplicate.
