### ISSUE TITLE
Option to install only vim.exe (not gVim)

### ISSUE THREAD

**Issue by aks2161989** [vim/vim-win32-installer#162]
Vim installer on Windows **always** installs gVim. 

![Screenshot (23)](https://user-images.githubusercontent.com/20129646/70930464-45992a80-205b-11ea-94f8-2abc84c1a9a4.png)

However, it would be great if gVim installation was optional. Those of us who like **vim** could install only vim and **not** gVim.

**Comment by chrisbra** [comment]
I don't really see the problem here. If you don't like gvim, simply do not use it. Those additional 4MB shouldn't really matter nowadays. I'd rather make the whole dialog simpler by removing options and not adding new options.

**Comment by aks2161989** [comment]
@chrisbra I agree, it's not a major issue. I figured it would allow a "cleaner" install.

**Comment by chrisbra** [comment]
closing

**Comment by simianeditions** [comment]
Not a big deal, but 4mb is still bloat if you'll never use them.
