### ISSUE TITLE
Upgrade to Python 3.8

### ISSUE THREAD

**Issue by mohd-akram** [vim/vim-win32-installer#167]

**Comment by chrisbra** [comment]
Can you please provide some arguments?

**Comment by mohd-akram** [comment]
Windows makes it very easy to have the latest Python version and it is currently available on the Windows store. Might as well have the latest version to use the new features.

**Comment by skywind3000** [comment]
+1 for python 3.8

**Comment by NewUserHa** [comment]
+1
python 3.8 has some well features like PEP 572, PEP 590, PEP 574, and asyncio on windows.

**Comment by chrisbra** [comment]
switched to python 3.8 as of 6360b74b3d2fe0efc43dd3c19cf57b7d7b5b081d

**Comment by skywind3000** [comment]
Thanks

**Comment by mohd-akram** [comment]
Thank you!

**Comment by NewUserHa** [comment]
and I found that updating vim or python alone is impossible is annoying. can't update python without the specific vim version, and can't update viim without the right python version
I don't know ruby but python always has new features in the recent major versions, so is it possible to support like 3.7-3.9 multiple versions at the same time?

**Comment by NewUserHa** [comment]
updating vim or python alone is impossible and pain except building ourselves.
can support multiple versions like 3.7-3.9 at the same time since python always has new features and planned to update a major every year https://www.python.org/dev/peps/pep-0602/.

**Comment by chrisbra** [comment]
no, that is not possible. We can only link one specific python version to Vim.

**Comment by NewUserHa** [comment]
ok.
