### ISSUE TITLE
Chrome flagging as virus

### ISSUE THREAD

**Issue by kres0345** [vim/vim-win32-installer#174]
I tried downloading 

> gvim_8.2.0260_x64.exe

 but it was flagged as a virus by Google Chrome _Version 80.0.3987.106 (Officiel version) (64-bit)_

**Comment by chrisbra** [comment]
According to [virustotal](https://www.virustotal.com/gui/url/34dcb1d78253355b14e31e84040cccf15b8fd78909f521469518a49fa1f214c8/detection), the file is clean. There is nothing we can do against this. Please raise an issue with the Chrome project for this.
