### ISSUE TITLE
last versions of vim.exe do not work properly with cmd.exe

### ISSUE THREAD

**Issue by jdarias** [vim/vim-win32-installer#179]
I noticed a weird behavior with v8.2.0579. 
When run on cmd.exe the cursor remains on the top left corner and it won't move. The status bar shows the line/column where it is, but it will stay on the top left of the window.

Also it seems that the default configuration is not loaded properly: when I enter a command, the command line jumps from bottom to top of the window.

If I press tab, it won´t show all the options at once.
Also, the cmd window content gets a bit garbled when i quit vim

I tested several versions, and v8.2.0539 is the last one that works properly on my system. 
I tried 8.2.0579, 8.2.0577 and 8.2.0566. All of them have this issue.

[Here is my vimrc](https://github.com/vim/vim-win32-installer/files/4484841/vimrc.txt)

I made a screencast to illustrate my point: first I load 539 which works as expected. Then I uninstall it and install 566. The difference in behavior can be seen in this version.
[Screencast](https://youtu.be/KB-mvwK98XQ)

Finally, it doesn't seem to happen with other console emulators, like the new Windows Terminal preview or conemu. Only happens with cmd.exe

**Comment by chrisbra** [comment]
I believe this problem has been introduced with patch [8.2.547](https://github.com/vim/vim/commit/e7f234120f71a75f0c7c2a67e0b70c6450c50a02) and was just yesterday fixed with patch [8.2.581](https://github.com/vim/vim/commit/81ccbf199f0d553efdd57bec9bb8e23d91d2fb0d)

Unfortunately, the build yesterday failed, so no new fixed version yet available.

**Comment by chrisbra** [comment]
Looks like the build failed just because of a flaky test. There is now https://github.com/vim/vim-win32-installer/releases/tag/v8.2.0582 that should fix that bug.
