### ISSUE TITLE
simplified chinese menu warning

### ISSUE THREAD

**Issue by haohaifeng002** [vim/vim-win32-installer#180]
gvim version: 8.2.613

The warning is as follows after opening gvim.exe on Windows OS:
```
处理 D:\Program Files\Vim\vim82\lang\menu_chinese_gb.936.vim 
时发生错误:
第  125 行:
E474: 无效的参数
```

The warning is disappeared after  
`menutrans Soft\ &Tabstop    软制表位宽度(Soft Tabstop)(&T)`
is changed to 
`menutrans Soft\ &Tabstop    软制表位宽度(&T)`

**Comment by chrisbra** [comment]
So it is about this file in the main vim Repository:

https://github.com/vim/vim/blob/1966c248814d5195edcd1208ed0e51e664a61283/runtime/lang/menu_chinese_gb.936.vim#L125

Please contact the maintainer of the file mentioned at the top of the file.

**Comment by haohaifeng002** [comment]
ok

**Comment by shunner** [comment]
Got it! Sorry for missing an escape of the space in translated text. Working on it and similar files.

**Comment by chrisbra** [comment]
I suppose @shunner will send updates to Bram then directly. Therefore closing this issue.
