### ISSUE TITLE
ship luajit binaries with the installer

### ISSUE THREAD

**Issue by prabirshrestha** [vim/vim-win32-installer#182]
Neovim ships with lua so would be good to also ship lua given these improvements:
https://github.com/vim/vim/pull/6063
https://github.com/vim/vim/pull/6098

Currently one needs to hunt for lua dlls and either add it in path or paste it beside the vim binaries. 

Neovim does use luajit instead of the latest lua as the performance improvements out weighs new language features. this would also make it consistent with neovim.

**Comment by chrisbra** [comment]
We do not ship python or lua or other dlls. I don’t think it is in the scope of this project to ship lua and what the neovim project does doesn’t really matter.

**Comment by prabirshrestha** [comment]
My primary reason for bundling lua is for perf. Looking at the source code seems like it is using lua instead of luajit which I'm also ok with.

There are multiple perf issues with vimscript which is very noticable and would like to use a language that is more easy to integrate with. Python/Ruby are difficult to get it working while with lua it is very simple.
https://github.com/prabirshrestha/vim-lsp/issues/633
https://github.com/prabirshrestha/vim-lsp/pull/635
https://github.com/natebosch/vim-lsc/issues/273

For linux/mac users it is not difficult since they can use their favorite package manager to install but for windows people need to go find and get the exact one. Hence I recommended if we can bundle lua.

**Comment by chrisbra** [comment]
I am not sure. We in general do not ship with the libraries for Python/Perl/Lua/Ruby etc. That would also make the archive quite a bit bigger.

If we start shipping with lua, the next person asks us to also ship the Python/Perl/Ruby etc libraries and I don't want to add this overhead to the packaging here. Plus, we will and up with a different distribution, than what the official downloads at vim.org uses which may lead to different issues.

The only thing I could imagine would be to offer an additional archive, which includes the lua/python/perl/ruby dlls in addition. @brammool @k-takata what are your thoughts on that?

**Comment by k-takata** [comment]
Lua is slightly different from other interfaces.

Python and Ruby don't work only with their DLLs. Some other modules are also needed.
Python and Ruby have installers and they can set $PATH, but Lua doesn't have an installer and user needs to set $PATH by himself.
Lua is small (e.g. lua53.dll is 400KB), so bundling it may not have much impact.

So, I think bundling Lua is acceptable. (Actually, I have my own [Vim package](https://github.com/k-takata/vim-kt) and it is shipped with lua53.dll.)
Not sure which is better, lua or luajit.
(Note that we need to update the build script and the NSIS script.)

**Comment by chrisbra** [comment]
> (Note that we need to update the build script and the NSIS script.)

yes, but since this deviates from the officially provided downloads from vim, I would very much prefer to have this change included in the vim.org repository as well.

**Comment by k-takata** [comment]
vim/vim#6143 was rejected.

**Comment by chrisbra** [comment]
Let's keep it still open. If the lua PR gains traction among the users it might still be feasible after all (and perhaps Bram re-considers).

**Comment by prabirshrestha** [comment]
In the mean time even though lua is not shipping by default is it possible to get a build as pat of release that is compiled against luajit instead of lua? Neovim uses luajit due to far better perf. https://luajit.org/performance_x86.html 

I primarily use plugins that are written in vimscript due to its compatibility and lua where I really need perf so using luajit would be better here.

Two options I can think of:
1. Ship 2 vim releases one compiled with lua and one with luajit.
2. Ship only one vim release compiled with luajit and have others manually compile with lua if needed.

Thoughts?

**Comment by hungpham3112** [comment]
> In the mean time even though lua is not shipping by default is it possible to get a build as pat of release that is compiled against luajit instead of lua? Neovim uses luajit due to far better perf. https://luajit.org/performance_x86.html
> 
> I primarily use plugins that are written in vimscript due to its compatibility and lua where I really need perf so using luajit would be better here.
> 
> Two options I can think of:
> 
> 1. Ship 2 vim releases one compiled with lua and one with luajit.
> 2. Ship only one vim release compiled with luajit and have others manually compile with lua if needed.
> 
> Thoughts?

Agree with that.
