### ISSUE TITLE
Please do not add version number to the default installation folder.

### ISSUE THREAD

**Issue by 9527KGG** [vim/vim-win32-installer#184]
Currently, the default installation folder is: eg "C:\Program Files\Vim\vim82\gvim.exe"

Request:
Please do not add version number to the default installation folder. So the folder should be either "C:\Program Files\Vim\gvim.exe" or "C:\Program Files\Vim\vim\gvim.exe"

Reason:
It's inconvenient when user upgrades to a new version while his/her script depends on the full path.

Eg, my script vim_edit.bat launches gvim.exe from "C:\Program Files\Vim\vim82\gvim.exe". Every time I upgrade gvim version, I have to upgrade the script file, which is inconvenient.

As a comparison, there no such issue on Linux because the default installation folder does not have version #, etc: /usr/bin/gvim.

Thanks.

**Comment by chrisbra** [comment]
This is out of the question for this repository here. I don't think this is going to change, as this is how Vim has behaved the last several years and many users are used to that. BTW, I don't understand why you need to give the full path, if your Vim is in the path, it doesn't matter where it resides.

**Comment by k-takata** [comment]
Currently, both (g)vim.exe and runtime files are installed in the `vim82` directory.
If we move only the executable files to `C:\Program Files\Vim`, then the issue will be solved.
But the installer program and the installer script should be modified.

**Comment by 9527KGG** [comment]
@chrisbra , Thanks. 

"if your Vim is in the path, it doesn't matter where it resides." -> eg besides gvim.exe "C:\Program Files\Vim\vim82" has other files (dll). If I add gvim.exe path to %path%, these dll could pollute the work environment. (It's possible, isn't it?)

About "BTW, I don't understand why you need to give the full path" -> I've a script to wrap the gvim.exe startup with customized parameters. Because gvim.exe is not in %path%, I need need specify full path of gvim.exe.

Why windows's behavior cannot just be consistent to Linux's behavior? I am mean no version number.

Thanks.

**Comment by chrisbra** [comment]
> Why windows's behavior cannot just be consistent to Linux's behavior? I am mean no version number.

Unix installation goes along with creating the $VIMRUNTIME path which includes the version like windows does. See `:echo $VIMRUNTIME` from within Vim.

**Comment by k-takata** [comment]
> Why windows's behavior cannot just be consistent to Linux's behavior? I am mean no version number.

(g)vim.exe itself supports such installation (see No. 3 of `:help $VIM`), but current installer doesn't support it as I explained in the previous comment.
