### ISSUE TITLE
Is it possible add old version tags?

### ISSUE THREAD

**Issue by wsdjeg** [vim/vim-win32-installer#185]
Hello, I want to test some plugin in old vim, and I have view all of the tags, and do not find old vim tags. can you add vim_64.zip for:

1. vim7.4.052 (ubuntu 14.04)
2. vim 7.4.629 ( Centos 6 7)

**Comment by k-takata** [comment]
Sorry, I don't want to add old builds. If you need an old release, please download it from the official site (vim.org) or build it by yourself.

**Comment by wsdjeg** [comment]
@k-takata sorry, I have search on the website many days, but can not find the old version download link, I am using a old laptop, it is too hard to build on this PC, does official site provide link for old version?

**Comment by k-takata** [comment]
Here is a list of releases:
https://gist.github.com/k-takata/fd0615181e71c873c8fcb7dac517911f

You can get this by the following commands:
```shell
$ (for i in `seq 1 13`; do curl "https://api.github.com/repos/vim/vim-win32-installer/releases?per_page=100&page=$i"; done) > releases.json
$ jq '.[].html_url' releases.json | sed -e 's/"//g' -e 's/^/* /' | sort > releases.md
```

It would be nice if we create this list on the wiki page, and automatically update it when a new release is created.

**Comment by wsdjeg** [comment]
OK thanks.

**Comment by k-takata** [comment]
Added the list in the wiki page.
https://github.com/vim/vim-win32-installer/wiki/List-of-Releases

**Comment by chrisbra** [comment]
On So, 30 Aug 2020, K.Takata wrote:

> Added the list in the wiki page.
> https://github.com/vim/vim-win32-installer/wiki/List-of-Releases

Cool. Unless you are planning to update this page automatically, I might 
be able to update it whenever I add the signed releases. It is already 
manual work, so it shouldn't add much burden if done regularly.

I also see you added my statistics from back then. I should probably 
update those as well. I see what I can do for that.

Christian
-- 
Deutschlands Schicksal:
Vor dem Schalter zu stehen.
Deutschlands Ideal:
Hinter dem Schalter zu sitzen.
		-- Kurt Tucholsky

**Comment by k-takata** [comment]
> Cool. Unless you are planning to update this page automatically, I might be able to update it whenever I add the signed releases. It is already manual work, so it shouldn't add much burden if done regularly.

I automated this: #192

And it would be nice if the signed files are also uploaded automatically.
It seems that SignPath provides a way to notify the completion of signing: https://about.signpath.io/documentation/build-system-integration#webhook-notifications
Maybe, a custom server that recognize the SignPath's webhook format is needed.

> I also see you added my statistics from back then.

I didn't change the statistics page at all.

**Comment by chrisbra** [comment]
cool +1
