### ISSUE TITLE
Fix install directory for 64-bit

### ISSUE THREAD

**Issue by adrian-constantin** [vim/vim-win32-installer#189]
Hello,

Installing the latest Win64 setup shows a default install directory of `C:\Program Files (x86)`. 

Can the directory be changed to `C:\Program Files` in this case please ?

**Comment by k-takata** [comment]
If you install 64-bit version without uninstalling 32-bit version, it will use `C:\Program Files (x86)`.

**Comment by terminatorul** [comment]
I did uninstall the 32-bit version first, however on a clean VM I noticed the latest package installs into Program Files as expected.
