### ISSUE TITLE
I need automatic update function

### ISSUE THREAD

**Issue by CreeperKong** [vim/vim-win32-installer#190]
The software is updated almost **every day**.

I hope developers can add a background automatic update service or "check for updates" function.

**Comment by k-takata** [comment]
> The software is updated almost **every day**.

It doesn't mean you have to update it every day.
Recent updates are almost for vim9script. If you are not interested in it, you don't need to update it so frequently.

**Comment by chrisbra** [comment]
I agree this would be nice, but I don't think anybody is working on that. PR would be certainly appreciated :)
On alternative would be to use the github API and script it yourself. Should not be too hard.

**Comment by CreeperKong** [comment]
All right.
