### ISSUE TITLE
The State of ActiveTCL

### ISSUE THREAD

**Issue by chrisbra** [vim/vim-win32-installer#194]
It looks like public downloads of ActiveTCL are no longer possible. The current URLs fail with a [connection reset](https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/updw6aaql5ejjjso). If you try to download locally, it will also fail. I tried to find other downloads for ActiveTCL (there are newer releases available, 8.6.9 and apparently also 8.6.10), but that requires to create an account at activestate.com which will then fork from the public repository into your local account. 

Stable Download links do not seem to be generally available.

So what to do? Disable the TCL interface in order to build new vim binaries? Find other tcl installations for windows?

**Comment by chrisbra** [comment]
possible alternatives:

- https://bitbucket.org/tombert/tcltk/downloads/
- https://www.irontcl.com/ 
- https://www.magicsplat.com/tcl-installer/index.html#downloads

**Comment by k-takata** [comment]
I have tried IronTcl locally before. I could build it fine, but now the version is a bit old: 8.6.7.
Other two look up to date, but I haven't tried.

I think that disabling TCL temporarily is a better workaround for now.

**Comment by chrisbra** [comment]
thanks, yes I agree with disabling.

**Comment by chrisbra** [comment]
might be able to have public download urls soon: https://community.activestate.com/t/public-download-of-activestatetcl/3181

**Comment by prabirshrestha** [comment]
Came here to try the `matchfuzzy` and noticed builds failing.

Ok removing or temporarily disabling.

Another option is to download the file and create a github release and upload it and download it from there instead. Ideally this would be good for other libraries too and won't depend on other websites going down.

**Comment by chrisbra** [comment]
fixed by 171d898820861933586bd5d37dbdf102220e15a9
