### ISSUE TITLE
Copy executable to run in Msys2 environment

### ISSUE THREAD

**Issue by duytrung** [vim/vim-win32-installer#201]
Hello,

I'm wondering how to configure the daily update of this vim in the Msys2 environment?

I know that I can copy the exe file to run in Mintty but the way vim was in Msys2 is quite different from Windows environment as far as I know.

Thank you for your suggestions

**Comment by chrisbra** [comment]
do you really need a daily update of your vim?

**Comment by duytrung** [comment]
no, just for fun. I visited and download newer version of vim at this github repo to my computer on a-few-day basis. Just after a more functional and stable version 👍

**Comment by k-takata** [comment]
If you are talking about `/usr/bin/vim.exe` in MSYS2, it is an MSYS2 application which is differ from a normal Win32 application.
You should update it by the `pacman` command, or you can build Vim from source and install it to `/usr/local/bin/vim.exe`.

**Comment by duytrung** [comment]
Thanks K-takata for your suggestion
