### ISSUE TITLE
Fail to load help.txt when vim installed in folder contained non-English character

### ISSUE THREAD

**Issue by zhufeng** [vim/vim-win32-installer#205]
When I type :h within vim, a error message show that "Sorry can't find help file "$VIMRUNTIME\doc\help.txt".

I tried to move the whole folder to a folder without any non-English character and the help system works well.

btw, my os is win 10 LTSC (1809 17763.1637).

And I tried some other versions of vim, seems that the bug affect specified version after vim 8.1 , and all vim 8.2 .

**Comment by chrisbra** [comment]
So where did you install vim?

**Comment by zhufeng** [comment]
> So where did you install vim?

d:\软件\gvim\

**Comment by k-takata** [comment]
Can you bisect it? You can find the releases here: https://github.com/vim/vim-win32-installer/wiki/List-of-Releases.
And what is your `encoding` setting?

**Comment by zhufeng** [comment]
> Can you bisect it? You can find the releases here: https://github.com/vim/vim-win32-installer/wiki/List-of-Releases.
> And what is your `encoding` setting?

Sorry I don't understand your meaning of ' bisect it '.
Now I downgrade my vim to 8.1.1002 and it works well.
My encoding setting in _vimrc file is :
`set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
`

**Comment by k-takata** [comment]
'bisect' means to find the suspicious version by bisection search (binary search).

> set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

Not `fileencodings`, what I'm asking is `encoding`.
What does `:set enc?` show?

**Comment by zhufeng** [comment]
> 'bisect' means to find the suspicious version by bisection search (binary search).
> 
> > set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
> 
> Not `fileencodings`, what I'm asking is `encoding`.
> What does `:set enc?` show?

encoding=cp936

**Comment by k-takata** [comment]
I think [8.1.1103](https://github.com/vim/vim/commit/0eb035c974c47e65d32439b48e5a056b370ad429) caused the issue.
However, even without this patch, Vim doesn't work when it is installed in a non-ASCII-character directory and 'enc' is set to utf-8.

**Comment by zhufeng** [comment]
> I think [8.1.1103](https://github.com/vim/vim/commit/0eb035c974c47e65d32439b48e5a056b370ad429) caused the issue.
> However, even without this patch, Vim doesn't work when it is installed in a non-ASCII-character directory and 'enc' is set to utf-8.

You're right, I tried some versions and the bug shows starting from 8.1.1103.
So any patch to apply for this bug?
Thanks.

**Comment by k-takata** [comment]
I've created a patch for this:
https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/tip/win32-vimdir-encoding.patch

**Comment by k-takata** [comment]
Fixed by [9.0.1313](https://github.com/vim/vim/commit/ce3189d56e867a2ffc077893b62f530d5b09150f).
