### ISSUE TITLE
has('python3') return 0

### ISSUE THREAD

**Issue by FlashIvano** [vim/vim-win32-installer#217]
version: 8.2.3046

**Comment by chrisbra** [comment]
That is because it is compiled with dynamic python. So you need to check `has('python3/dyn')`. And I blieve this only works, if you have python3 dll available.

**Comment by FlashIvano** [comment]
I found the solution.

The reason is that the python verison when complied is 3.9

check `:version` reuslt:

```
Compilation: ... -DDYNAMIC_PYTHON_3_DLL=\"python39.dll\" ...
```

But I installed Python 3.8 on my computer.

The solution is adding the following content to vimrc:

```
set pythonthreedll=python38.dll
```

Also require Python path is in $PATH env, and python 32/64-bit arch is same to gvim.

**Comment by chrisbra** [comment]
It would be nice, if you included much more of your original problem in your problem report :/ 

Note: that the compiled version is also mentioned at the README of this project. 

Since the issue is resolved, I am closing this.
