### ISSUE TITLE
what is libsodium.dll

### ISSUE THREAD

**Issue by OsmondGao** [vim/vim-win32-installer#220]
version:gvim_8.2.3159_x64
error:missing libsodium.dll

**Comment by chrisbra** [comment]
Oh, was it not copied into the runtime folder? You can get that from here: https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18-msvc.zip From the archive, please copy over libsodium\x64\Release\v140\dynamic\libsodium.dll into your vim runtime path.

**Comment by chrisbra** [comment]
wait a second, did you use the installer or the zip archive?

**Comment by OsmondGao** [comment]
I use installer.And I resolved it by get dll from other site.

**Comment by chrisbra** [comment]
@k-takata I think we need this patch for the installer:
```patch
diff --git a/nsis/gvim.nsi b/nsis/gvim.nsi
index 3fe0279b7..3a6653f7c 100644
--- a/nsis/gvim.nsi
+++ b/nsis/gvim.nsi
@@ -346,6 +346,9 @@ Section "$(str_section_exe)" id_section_exe
        File /oname=gvim.exe ${VIMSRC}\gvim_ole.exe
 !if /FileExists "${VIMSRC}\vim${BIT}.dll"
        File ${VIMSRC}\vim${BIT}.dll
+!endif
+!if /FileExists "${VIMRT}\libsodium.dll"
+       File ${VIMRT}\libsodium.dll
 !endif
        File /oname=install.exe ${VIMSRC}\installw32.exe
        File /oname=uninstall.exe ${VIMSRC}\uninstallw32.exe
```

what do you think?

**Comment by OsmondGao** [comment]
@chrisbra Can you resolve the issue #218 ?It is exist in the latest version

**Comment by chrisbra** [comment]
No I cannot, because I do not understand it.

**Comment by k-takata** [comment]
@chrisbra Looks good.

**Comment by k-takata** [comment]
I changed v8.2.3159 to pre-release.

I also think that it might be better to support dynamic loading for libsodium.

**Comment by chrisbra** [comment]
Don't know how to do the dynamic loading, then we should perhaps revert that.

**Comment by k-takata** [comment]
I haven't checked it yet at all, but I think we need a similar way to if_xxx or libiconv.

**Comment by chrisbra** [comment]
okay. In that case let's just revert enabling sodium.

**Comment by chrisbra** [comment]
closing for now
