### ISSUE TITLE
Version 8.2.3318 detected as a threat (Trojan:Script/WacatacB!ml)

### ISSUE THREAD

**Issue by ImJoakim** [vim/vim-win32-installer#224]
Hey there, 
When updating Vim to version 8.2.3318, it will get detected and blocked:

![image](https://user-images.githubusercontent.com/52826317/128776214-a3fef550-64b0-434e-8ad9-0a158bbc63bb.png)

This does not happen to any other version (that I can find).

**Comment by chrisbra** [comment]
this is most likely a false positive. You can always check the files using e.g. virustotal, here are the reports for version 8.2.3318. You did not say, what binary you used, so I have scanned all installers:

https://www.virustotal.com/gui/url/33e68b0b4f2564db205d1ad7e94979412cb4999627aebfe68e78b48f5a19e464/detection
https://www.virustotal.com/gui/url/8268023e153c5ca38dc6045f6dbbfd869af55f5f0cdeaf46687fefe8fb0ce690/detection
https://www.virustotal.com/gui/url/f4c1106c9ee2459f9b6e14b83f7bad0ced69c2077589c664b9459e3ffbd7a3e3/detection
https://www.virustotal.com/gui/url/7d193e83611f8e885103b7198d3e1efbffbfcaa2a2fbfea1b0043cd203192154/detection

I suggest complaining to your AV vendor about it. See also #174 and similar issues here .
