### ISSUE TITLE
plugins using python3 crash vim on windows

### ISSUE THREAD

**Issue by LollipopFt** [vim/vim-win32-installer#225]
this has been a longstanding issue for vim.
steps to reproduce:
1. open vim with python3/dyn and python/dyn support
2. open a python-reliant plugin (in this case ultisnip)
3. navigate to any file and try to type something in insert mode (this problem persists with or without nerdtree [and using :o command], which i used for ease of navigation)
4. vim gives an error message with something about python before crashing
5. note: this has got nothing to do with how there is a swp file for that file either. the entire reason the swp file remained in the first place was that vim had crashed on me before i could save the file.

https://user-images.githubusercontent.com/62802897/129758801-98cbe28f-c287-42b1-bfdd-16d22d83b0f3.mp4

thanks!

**Comment by k-takata** [comment]
I captured the error message:
![image](https://user-images.githubusercontent.com/840186/129846192-8c51ed4f-331f-4276-b163-bdf87f0dd7bc.png)

It looks that you are using python 3.9 from miniconda, and the python failed to load the 'encodings' module.
Actually, the vim binaries in this project are tested only with the official python. So, I don't know whether they work with miniconda's python. Could you try with the official python 3.9?

**Comment by k-takata** [comment]
Or, try setting the 'pythonthreehome' option.

**Comment by LollipopFt** [comment]
> 
> 
> Or, try setting the 'pythonthreehome' option.

this worked for me, thank you!
