### ISSUE TITLE
update 8.2.2425 to 8.2.3757 , has('python3') 0, already set pythonthreedll 

### ISSUE THREAD

**Issue by WillDawnlll** [vim/vim-win32-installer#234]
Yesterday update gvim by new release exe , then python3 dont work .
In version command result,  i noticed  ` -DDYNAMIC_PYTHON3_DLL=\"python310.dll\"` 
pythonthreedll  its always be setup

**Comment by chrisbra** [comment]
so what do you have pythonthreedll set to? What previous version did you use, what python have you installed?

**Comment by k-takata** [comment]
You need to install Python 3.10.

**Comment by WillDawnlll** [comment]
thanks for help.
pythonthreedll is python37 path , but is work in 8.2.2425 .
and 8.2.2425 `-DDYNAMIC_PYTHON3_DLL` is `python39.dll`.  So I ruled out this situation before.
i  wiill try install python 3.10...there is already 5 py verison...emm..

**Comment by chrisbra** [comment]
yes, there was a request to update the python dependency to 3.10  since it was released. I guess we cannot make everybody happy

**Comment by WillDawnlll** [comment]
py310 work good, thanks again....just a little confused, why can I use py37 dll   with dependency  3.9...Actually forget it, now it's okay , It should be updated in time ...

**Comment by k-takata** [comment]
> why can I use py37 dll with dependency 3.9

Normally, you should use the same version of the dll with the version which was used for compiling.
However, it seems that python 3.7 to 3.9 were binary compatible by chance.
