### ISSUE TITLE
Python 3.9+ doesn't support Windows 7

### ISSUE THREAD

**Issue by uralets** [vim/vim-win32-installer#236]
subj
If you rely on a python3 plugin while using Windows 7, you're out of luck with these builds.

**Comment by chrisbra** [comment]
Well, to be fair, this Windows 7 support ended in january 2020, so almost 2 years ago.

For those using Windows 7 you can:
- self-compile Vim with older python 3 version
- Use a previous build, e.g. https://github.com/vim/vim-win32-installer/releases/tag/v8.2.3614 (not sure if Python 3.9) is still supported on Windows 7)


In any case, this is nothing we can fix here. Please complain to the Python developers.
