### ISSUE TITLE
no 'dnd', :python3 is disabled with v8.2.3802

### ISSUE THREAD

**Issue by elig0n** [vim/vim-win32-installer#237]
I have installed both v8.2.3802 64bit and 32bit windows versions but could not find they have 'dnd' (drag & drop support) and the :python3 command was disabled (despite 'python3' being enabled in `:ver`)

**Comment by chrisbra** [comment]
1) Regarding Python:
you need to install python3.10 separately and make sure it's in your path. Make sure it's also the same architecture as your vim version. That means, you need 64bit for 64bit vim, etc. 
2) Regarding `dnd`
It seems, this feature is only available in the GTK Linux Gui, not available on Windows.
