### ISSUE TITLE
gVim throwing errors on startup with v8.2.4167

### ISSUE THREAD

**Issue by sigzero** [vim/vim-win32-installer#238]
I was using v8.2.4148 with no errors when starting up gVim. When I put v8.2.4167 in place, gVim now throws up the errors in the attached screenshot. I keep up to date with these and this is the first one that has caused any issues like this.

![vim_error](https://user-images.githubusercontent.com/540937/150545797-806861d0-dee0-4542-959f-8b5912fb4824.png)

**Comment by k-takata** [comment]
It looks that this is the same with https://github.com/vim/vim/issues/9580.
This should be fixed in the tomorrow's release.

**Comment by chrisbra** [comment]
closing
