### ISSUE TITLE
Change linespace also change height of statusline

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim-win32-installer#243]
step to reproduce:

1. use minimal vimrc:
```
call plug#begin('~/vimfiles/plugged')
Plug 'itchyny/lightline.vim'
call plug#end()
set linespace=8
set statusline=2
```
2. see some minigap in statusline:
![image](https://user-images.githubusercontent.com/75968004/153333384-52698431-f8ad-4747-8a37-31b2dede9f0c.png)
Expectation:
changing `linespace` doesn't change height of statusline in GUI Vim.

**Comment by k-takata** [comment]
`linespace` inserts spaces between the lines, so this is the expected behavior.
