### ISSUE TITLE
Why I can't run C code in terminal mode?

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim-win32-installer#249]
If I run `:!clang % -o %<.exe && %<.exe` it works fine. But if I have a mapping with terminal it's broken:

        au FileType c nnoremap <buffer> <Enter> :up <bar> vert term clang % -o %<.exe && %<.exe <Cr>

Is it a problem with terminal mode or something?

Thanks for helping.

**Comment by k-takata** [comment]
Please ask user questions on the vim_use mailinglist or use vi.stackexchange.com. This here is a bug tracker for problems with the Vim installer. If you think it is a bug of Vim itself, please report it to the [main repository](https://github.com/vim/vim/issues) with the minimal reproducible steps.
We cannot provide individual help here. Closing.
