### ISSUE TITLE
Could not load python310.dll. The specified module could not be found.

### ISSUE THREAD

**Issue by hungpham3112** [vim/vim-win32-installer#251]
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb  2 2022 23:02:45)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-4286
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +cmdline_info       +extra_search       +langmap            +num64              +scrollbind         -termresponse       -vtp
+arabic             +comments           -farsi              +libcall            +ole                +signs              +textobjects        +wildignore
+autocmd            +conceal            +file_in_path       +linebreak          +packages           +smartindent        +textprop           +wildmenu
+autochdir          +cryptv             +find_in_path       +lispindent         +path_extra         -sodium             -tgetent            +windows
+autoservername     +cscope             +float              +listcmds           +perl/dyn           +sound              +timers             +writebackup
+balloon_eval       +cursorbind         +folding            +localmap           +persistent_undo    +spell              +title              -xfontset
-balloon_eval_term  +cursorshape        -footer             +lua/dyn            +popupwin           +startuptime        +toolbar            -xim
+browse             +dialog_con_gui     +gettext/dyn        +menu               -postscript         +statusline         +user_commands      +xpm_w32
++builtin_terms     +diff               -hangul_input       +mksession          +printer            -sun_workshop       +vartabs            -xterm_save
+byte_offset        +digraphs           +iconv/dyn          +modify_fname       +profile            +syntax             +vertsplit          
+channel            +directx            +insert_expand      +mouse              +python/dyn         +tag_binary         +vim9script         
+cindent            -dnd                +ipv6               +mouseshape         +python3/dyn        -tag_old_static     +viminfo            
+clientserver       -ebcdic             +job                +multi_byte_ime/dyn +quickfix           -tag_any_white      +virtualedit        
+clipboard          +emacs_tags         +jumplist           +multi_lang         +reltime            +tcl/dyn            +visual             
+cmdline_compl      +eval               +keymap             +mzscheme/dyn       +rightleft          -termguicolors      +visualextra        
+cmdline_hist       +ex_extra           +lambda             +netbeans_intg      +ruby/dyn           +terminal           +vreplace           
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6   -DFEAT_XPM_W32     -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python310.dll\" -DFEAT_MZSCHEME -I "C:\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_da32rk.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_da32rk.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby300.dll\" -DRUBY_VERSION=30 -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /nologo /opt:ref /LTCG /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64 version.lib  winspool.lib comctl32.lib  libcmt.lib oleaut32.lib  /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python310.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug
```

Output `:verbose set pythonthreedll` , `:verbose set pythonthreehome`  :
```
pythonthreedll='C:\Users\hungpham\scoop\apps\python\current\python310.dll'
	Last set from ~\vimfiles\autoload\general_settings.vim line 20
```
```
pythonthreehome='C:\Users\hungpham\scoop\apps\python\current\'
	Last set from ~\vimfiles\autoload\general_settings.vim line 21
```

I'm using scoop for downloading python. Gvim gave me this error when opening:

![image](https://user-images.githubusercontent.com/75968004/155847959-a7092788-9674-4d90-b3d3-76c9533c5bba.png)

**Comment by chrisbra** [comment]
And the file exists? Are those also 64bit? Why does it say nvim command? Can you please provide a minimal vimrc example?

**Comment by hungpham3112** [comment]
> And the file exists? Are those also 64bit? Why does it say nvim command? Can you please provide a minimal vimrc example?
> […](#)
> Am 26.02.2022 um 16:03 schrieb hungpham3112 ***@***.***>: ﻿ VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 2 2022 23:02:45) MS-Windows 64-bit GUI version with OLE support Included patches: 1-4286 Compiled by ***@***.*** Huge version with GUI. Features included (+) or not (-): +acl +cmdline_info +extra_search +langmap +num64 +scrollbind -termresponse -vtp +arabic +comments -farsi +libcall +ole +signs +textobjects +wildignore +autocmd +conceal +file_in_path +linebreak +packages +smartindent +textprop +wildmenu +autochdir +cryptv +find_in_path +lispindent +path_extra -sodium -tgetent +windows +autoservername +cscope +float +listcmds +perl/dyn +sound +timers +writebackup +balloon_eval +cursorbind +folding +localmap +persistent_undo +spell +title -xfontset -balloon_eval_term +cursorshape -footer +lua/dyn +popupwin +startuptime +toolbar -xim +browse +dialog_con_gui +gettext/dyn +menu -postscript +statusline +user_commands +xpm_w32 ++builtin_terms +diff -hangul_input +mksession +printer -sun_workshop +vartabs -xterm_save +byte_offset +digraphs +iconv/dyn +modify_fname +profile +syntax +vertsplit +channel +directx +insert_expand +mouse +python/dyn +tag_binary +vim9script +cindent -dnd +ipv6 +mouseshape +python3/dyn -tag_old_static +viminfo +clientserver -ebcdic +job +multi_byte_ime/dyn +quickfix -tag_any_white +virtualedit +clipboard +emacs_tags +jumplist +multi_lang +reltime +tcl/dyn +visual +cmdline_compl +eval +keymap +mzscheme/dyn +rightleft -termguicolors +visualextra +cmdline_hist +ex_extra +lambda +netbeans_intg +ruby/dyn +terminal +vreplace system vimrc file: "$VIM\vimrc" user vimrc file: "$HOME\_vimrc" 2nd user vimrc file: "$HOME\vimfiles\vimrc" 3rd user vimrc file: "$VIM\_vimrc" user exrc file: "$HOME\_exrc" 2nd user exrc file: "$VIM\_exrc" system gvimrc file: "$VIM\gvimrc" user gvimrc file: "$HOME\_gvimrc" 2nd user gvimrc file: "$HOME\vimfiles\gvimrc" 3rd user gvimrc file: "$VIM\_gvimrc" defaults file: "$VIMRUNTIME\defaults.vim" system menu file: "$VIMRUNTIME\menu.vim" Compilation: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32 -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DFEAT_XPM_W32 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python310.dll\" -DFEAT_MZSCHEME -I "C:\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_da32rk.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_da32rk.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby300.dll\" -DRUBY_VERSION=30 -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi Linking: link /nologo /opt:ref /LTCG /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib /machine:AMD64 version.lib winspool.lib comctl32.lib libcmt.lib oleaut32.lib /nodefaultlib:lua54.lib /STACK:8388608 /nodefaultlib:python27.lib /nodefaultlib:python310.lib "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug Output :verbose set pythonthreedll , :verbose set pythonthreehome : pythonthreedll='C:\Users\hungpham\scoop\apps\python\current\python310.dll' Last set from ~\vimfiles\autoload\general_settings.vim line 20 pythonthreehome='C:\Users\hungpham\scoop\apps\python\current\' Last set from ~\vimfiles\autoload\general_settings.vim line 21 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.

I downloaded python with `scoop install python` , and python is 64bit. I don't know why it say nvim command. Maybe coc uses it .

To reproduce:
1. download python3.10 `scoop install python` -> this is 64-bit.  Download vim-nightly `scoop install vim-nightly@8.2.4286` -> this is 64-bit too.
2. Create a file `test.vim`:
```
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/vimfiles/plugged')
Plug 'https://github.com/neoclide/coc.nvim.git', {'branch': 'release'}
call plug#end()
set pythonthreedll='~\\scoop\\apps\\python\\current\\python310.dll'
set pythonthreehome='~\\scoop\\apps\\python\\current\\'

```
3. run `vim -c test.vim`
4. `:python3 import sys;print(sys.version)` and see message.

Second way:

**Comment by hungpham3112** [comment]
> > set pythonthreedll='~\scoop\apps\python\current\python310.dll'
> 
> Don't use single quotes when you use the `:set` command.

```
set pythonthreedll="~/scoop/apps/python/current/python310.dll"
set pythonthreehome="~/scoop/apps/python/current"
```
I changed to this but it still said:
![image](https://user-images.githubusercontent.com/75968004/155870219-2f6080c2-a96f-4838-a007-b9d69ad729f1.png)
