### ISSUE TITLE
Request: Include a unique string in signed release patch notes

### ISSUE THREAD

**Issue by idbrii** [vim/vim-win32-installer#265]
Currently, to find a signed release, you must search the [releases page](https://github.com/vim/vim-win32-installer/releases) for the lock emoji because the letters are a substring of "Unsigned Files":

> 🔒 Signed Files:
> 🔓 Unsigned Files:

## Proposed Solution

Include "This release includes signed files." above the "🔒 Signed Files" line:
https://github.com/vim/vim-win32-installer/blob/405637ccf3d4d8c5d935c4abddd1484fbe7d7a78/appveyor.yml#L82-L83

Then people could search for "includes signed" which is easier to type.

I assume being included in that comment means it would only be included in releases that have signed files?

**Comment by chrisbra** [comment]
Releasing the signed artifacts is still a half-manual processs, so I can add that line as well once I am releasing it.
