### ISSUE TITLE
'winget install vim.vim' fails silently

### ISSUE THREAD

**Issue by yrro** [vim/vim-win32-installer#269]
### Steps to reproduce

```
PS C:\Windows\System32> winget install vim.vim
Found Vim [vim.vim] Version 8.2.5136
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Successfully installed
```

But `C:\Program Files\Vim` doesn't exist and Vim is not installed.

If I run with `-i` then the Vim installer appears, and I can step through it, But when it comes to actually copying files to `C:\Program Files`. I get:

```
---------------------------
Vim 8.2 (x64) Setup
---------------------------
Error opening file for writing: 



C:\Program Files\Vim\vim82\gvim.exe



Click Abort to stop the installation,

Retry to try again, or

Ignore to skip this file.
---------------------------
Abort   Retry   Ignore   
---------------------------
```

It looks like the installer is not being launched with elevated privileges.

With the other things I've installed via winget, I've been prompted to elevate when it launches their installers.

### Expected behaviour

Vim should be installed

### Version of Vim

8.2.5136

### Environment

Windows 10 21H2
x64

**Comment by chrisbra** [comment]
Isn't that an issue with winget?

**Comment by k-takata** [comment]
It seems that there is a setting named "ElevationRequirement" starting from v1.1.0:
https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.1.0/manifest.singleton.1.1.0.json
Maybe we can use this?

**Comment by chrisbra** [comment]
Okay, then please create an issue at the following repo 
https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/vim/vim/8.2.5076
