### ISSUE TITLE
Windows binary version not provided for download as usual

### ISSUE THREAD

**Issue by duytrung** [vim/vim-win32-installer#27]
Hi,

I often check for the recent version of vim released here. However, in a week, only source zips were provided. 

Was there any big issue with the site?

Thanks

TN

**Comment by k-takata** [comment]
It is because the test fails.
See: https://groups.google.com/d/msg/vim_dev/Q28MVucLK0A/q0OQBqL_DAAJ

**Comment by chrisbra** [comment]
Yes, we could theoretically disable that test, but I rather not do it currently, hoping Bram finds a way to fix it soon. If the issue isn't solved within say 2 weeks, we should actually disable the test, I think.

**Comment by chrisbra** [comment]
fixed
