### ISSUE TITLE
Publish releases to Windows Package Manager (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [vim/vim-win32-installer#271]
**Is your feature request about something that is currently impossible or hard to do? Please describe the problem.**

No, it is easy to implement in my opinion.

**Describe the solution you'd like**

With every new release of Vim, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by chrisbra** [comment]
I had a look at winget some time ago and automatic update of packages did not see to be possible back then: https://github.com/microsoft/winget-pkgs/issues/2399 Perhaps that changed, so if you are up for a PR, that allows this, I am all for it :)

**Comment by vedantmgoyal2009** [comment]
@chrisbra I've created the pull request. Please review and merge :)
