### ISSUE TITLE
Trojan detected at install on Windows 10

### ISSUE THREAD

**Issue by phourglass** [vim/vim-win32-installer#275]
### Steps to reproduce

1. Install from gvim_9.0.0040_x64.exe onto system with windows10 and defender

### Expected behaviour

Warning: Trojan:Script/Wacatac.B!ml in file C:\Program Files\Vim\vim90\install.exe
Same warning if downloading the zip.
No warning if installing from the signed executable.

False positive or something more serious?
Thanks
Philippe

capture (os is in french)
![image](https://user-images.githubusercontent.com/46864536/177388621-0b77e61e-8ef6-4b1c-ac80-584943ff8a41.png)

### Version of Vim

gvim_9.0.0040_x64.exe

### Environment

Windows 10 21H2 64 bits
Defender up to date

**Comment by chrisbra** [comment]
According to Virustotal the file is clean: https://www.virustotal.com/gui/url/62d219e184dfb559f60629139ec3a3a0b3a87202a4c926a4bbc4843ddba9adbd


BTW: There is nothing we can do here regarding false positives. Please complain to your AV vendor for this.

See also the other (closed) issues here: https://github.com/vim/vim-win32-installer/issues?q=is%3Aissue+is%3Aclosed+virus
