### ISSUE TITLE
Binaries in winget repository are not up-to-date

### ISSUE THREAD

**Issue by gcrtnst** [vim/vim-win32-installer#279]
### Steps to reproduce

The version of Vim installed by `winget install vim.vim` is 9.0.0050, which is over a month old. GitHub Actions seems to be failing.

### Expected behaviour

should be able to install the latest Vim using winget

### Version of Vim

9.0.0050

### Environment

- Windows version: Windows 10 version 21H2 (OS Build 19044.1826)
- winget version: v1.3.2091

**Comment by chrisbra** [comment]
Hm, it seems the personal access token needs to have the workflow scope now. 

@vedantmgoyal2009 can you please confirm, does the winget actions workflow now require the personal access token to have the *workflow* scope? 

Because github actions fails with this message:
```
 Yaml file created: D:\a\vim-win32-installer\vim-win32-installer\winget-pkgs\manifests\v\vim\vim\9.0.0213\vim.vim.locale.en-US.yaml
  
  Yaml file created: D:\a\vim-win32-installer\vim-win32-installer\winget-pkgs\manifests\v\vim\vim\9.0.0213\vim.vim.installer.yaml
  
  Yaml file created: D:\a\vim-win32-installer\vim-win32-installer\winget-pkgs\manifests\v\vim\vim\9.0.0213\vim.vim.yaml
  Manifest validation succeeded.
  HEAD is now at f79aa8fb42 Updating manifests/a/Alibaba/Yuque/.validation (#69646)
  To https://github.com/vim/winget-pkgs.git
   ! [remote rejected]       vim.vim-9.0.0213-576A39CBE9E232 -> vim.vim-9.0.0213-576A39CBE9E232 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/spellCheck.yaml` without `workflow` scope)
  error: failed to push some refs to 'https://github.com/vim/winget-pkgs.git'
aborted: you must first push the current branch to a remote, or use the --head flag
```

**Comment by vedantmgoyal2009** [comment]
Either of the two things can be done:
- Give workflow permission to the token.
- Manually update the fork.

When the action was made, there were no workflows in microsoft/winget-pkgs. But now, there's a workflow for spell checking. So it is suggested to give the token workflow permission.

BTW, I don't know why GitHub CLI doesn't fail if it cannot push to the repository successfully. If you know anything in this regard, please help.

**Comment by chrisbra** [comment]
Hm,

> Give workflow permission to the token.

Then this should be documented at: https://bittu.eu.org/docs/wr-intro/ (it still mentions *public_repo*) 
I am a bit worried as it seems workflow permissions include a lot more permissions. I wonder if this could cause problems 🤔 

> Manually update the fork.

I assume you mean this? 
![image](https://user-images.githubusercontent.com/244927/184601714-137a9735-de7a-4f66-925f-e18b67efe077.png)


Thanks,
Chris

**Comment by vedantmgoyal2009** [comment]
> I assume you mean this?

Yes.

**Comment by chrisbra** [comment]
I have done that. Let's see if we it works with the next run. Thanks @vedantmgoyal2009 !

**Comment by vedantmgoyal2009** [comment]
Welcome 🙂

**Comment by chrisbra** [comment]
winget packages have been updated. So let me close it now.

**Comment by gcrtnst** [comment]
Thank you!
