### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by i-give-up** [vim/vim-win32-installer#28]
I'm not too familiar with software licenses, but should there be a License file in this repository?

**Comment by chrisbra** [comment]
Most of the work here has been done by @k-takata. So I'll leave the question to which license applies to him. I usually use the Vim license for my Vim related work, but not sure if this applies here.

**Comment by k-takata** [comment]
> I usually use the Vim license for my Vim related work

So do I.
Let's use the Vim license for the scripts in this repository.
