### ISSUE TITLE
New x64 builds after v9.0.0354 have apparently not been including any of the new patches

### ISSUE THREAD

**Issue by davea1** [vim/vim-win32-installer#281]
### Steps to reproduce

Download gvim_9.0.0372_x64.zip and extract.

Run Vim (or gVim) and execute the command `:version`

Output contains:
Included patches: 1-354

Note - According to this page, there have apparently been no new commits since "vim: Import v9.0.0354"  on Sept 1:
https://github.com/vim/vim-win32-installer/commits/master

### Expected behaviour

Output should contain:
Included patches: 1-372

### Version of Vim

9.0.0372

### Environment

Windows 10 Pro 64-bit

gvim_9.0.0372_x64.zip

**Comment by chrisbra** [comment]
oh, I broke it accidentally. Sorry should be fixed with the next release.

**Comment by chrisbra** [comment]
should be fixed with https://github.com/vim/vim-win32-installer/releases/tag/v9.0.0378

**Comment by davea1** [comment]
Verified. Thanks!
