### ISSUE TITLE
Winget automatic submission

### ISSUE THREAD

**Issue by albertosantini** [vim/vim-win32-installer#283]
In the README of this project: 

> This repository also contains a github actions CI-step for uploading the binaries to the winget repository.
> This means, the (unsigned) nightly builds will be automatically uploaded and submitted to the [winget repository](https://github.com/microsoft/winget-pkgs/).

The latest version of `vim.vim` is 9.0.500

```
$ winget search vim.vim
Name Id      Version  Source
-----------------------------
Vim  vim.vim 9.0.0500 winget
```

At the moment, the latest version is `v9.0.0969`. 
I was wondering if there is any issue blocking the automatic submission or it is intentional.

Thanks for your efforts.

**Comment by chrisbra** [comment]
hm, I haven't noticed and the github actions status is successful. But there are errors:

> Yaml file created: D:\a\vim-win32-installer\vim-win32-installer\winget-pkgs\manifests\v\vim\vim\9.0.0619\vim.vim.locale.en-US.yaml
>   
>   Yaml file created: D:\a\vim-win32-installer\vim-win32-installer\winget-pkgs\manifests\v\vim\vim\9.0.0619\vim.vim.installer.yaml
>   
>   Yaml file created: D:\a\vim-win32-installer\vim-win32-installer\winget-pkgs\manifests\v\vim\vim\9.0.0619\vim.vim.yaml
>   Manifest validation succeeded.
>   HEAD is now at 335bf06355 Modify: HermannSchinagl.LinkShellExtension version 3.9.3.5 (#49982)
>   To https://github.com/vim/winget-pkgs.git
>    ! [remote rejected]       vim.vim-9.0.0619-14FEEDB341AB92 -> vim.vim-9.0.0619-14FEEDB341AB92 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/spellCheck.yaml` without `workflow` scope)
>   error: failed to push some refs to 'https://github.com/vim/winget-pkgs.git'
> aborted: you must first push the current branch to a remote, or use the --head flag

ping @vedantmgoyal2009

**Comment by vedantmgoyal2009** [comment]
I guess you had given workflow permission to the token previously. Had you removed it afterwards?

**Comment by chrisbra** [comment]
no, I have never changed the permission. We have one token with `public_repo` permission, which is the scope documented at your repo: https://github.com/vedantmgoyal2009/winget-releaser

I remember from last time, I had to sync the fork of vimget-pkgs. I have now done that.

**Comment by albertosantini** [comment]
Ok... Submission restored.
For instance, the latest one: https://github.com/microsoft/winget-pkgs/pull/81118
