### ISSUE TITLE
Strange characters in console - only from this installer builds

### ISSUE THREAD

**Issue by zewpo** [vim/vim-win32-installer#294]
### Steps to reproduce

1. Run the installer, full options
2. open up cmd.exe,
3. start; vim --clean -U NONE
4. open help;  h:
5. use mouse visual select some text, and drag the visual selection around a bit.
6. see weird characters;
![image](https://user-images.githubusercontent.com/10286211/210158098-32e01458-5a48-448b-897f-be41d93bc982.png)

### Expected behaviour

Expect no weird characters.

I couldn't get it to occur when I compile the same patch levels myself.  I only see the problem with these appveyor builds.

I copied the appveyor.bat file, and tried to reproduce the build as close as possible to what appveyor is doing.  But, I did have to make a couple of changes;

Python version to 3.11.1
set PYTHON3_VER=311
set PYTHON3_RELEASE=3.11.1

Ruby version from 3.0 to 3.2
set RUBY_VER=32
set RUBY_API_VER_LONG=3.2.0
set RUBY_BRANCH=ruby_3_2
set RUBY_RELEASE=3.2.0-1

and some manual steps to get ruby to compile and install - the configure step was failing due to unfound header files.

The only other difference I could think of, is that appveyor.yml file mentions Visual Studio 2015, but I'm using Visual Studio 2022.

I'll install increasingly older versions until I find which one it starts at.  Will update what I find.

### Version of Vim

gvim_9.0.1097_x64.exe, gvim_9.0.1117_x64.exe,  and gvim_9.0.1122_x64.exe

### Environment

Windows 11 21H2

**Comment by zewpo** [comment]
Update - problem is happening in all releases from 1085.  
Problem is not happening in 1082 and earlier.

I'd like to see if my PR [9.0.1084] causes the problem.  Now, since I can't reproduce it locally, can I try submitting a patch to you guys to run it on appveyor?  I don't want to bother Bram with another PR unless we can confirm that it's going to fix it.

**Comment by zewpo** [comment]
I submitted PR anyway, reverting the possible changes that I could see might have have caused this - it removes unnecessary complexity even if it doesn't solve this issue.

**Comment by chrisbra** [comment]
okay cool. I think since #292 CI will build new artifacts even for PRs. I just don't know, if those artifacts are available for download

**Comment by zewpo** [comment]
Thanks @chrisbra 

The good news, I can see the artifacts on PRs to the vim repo, download them, and quickly replicate the issue on my pc.  I dont have to wait for you guys to do a build.

The bad news, the issue is still happening.

The good news, I have a way to work on it now and see results. :)

**Comment by zewpo** [comment]
@chrisbra 

It's not caused by my PRs.

I can now replicate the problem on my PC, by building vim with VS 2015, instead of VS 2022.  
It's caused by building with VS 2015, or the older Win SDK that VS 2015 uses.

The exact same source code, just a different builder, and it fails.

I've cloned this repo, as well as created my own appveyor account, and testing out how to use newer versions of VS, will provide some ideas how we could maybe resolve it in the next day or so.

**Comment by chrisbra** [comment]
hm, perhaps we can migrate to Visual Studio 2022

https://github.com/vim/vim-win32-installer/blob/19eb032585cf24c5bf6f9a6ba992fc3806e6bd0c/appveyor.yml#L3

https://www.appveyor.com/docs/windows-images-software/

not sure if this has any impact on the target system that vim can run on...

**Comment by zewpo** [comment]
Yes, that is what I've been working on, you can see it here if you want;

https://github.com/zewpo/vim-win32-installer

I've been trying the image: Visual Studio 2022
I got it working mostly.  Some of the pre-requisites are already pre-installed in this newer image, - and that was causing the bat file to hang in some places.    Fixing that up, now the Install, compile and build steps are mostly sorted now, just trying to figure out some of the steps that work with the NSIS packaging.

**Comment by zewpo** [comment]
with regards to target system - I've got a Win 7 Virtual Machine on my laptop that I can do some manual tests on, after I get the NSIS installer working - to see if there are any obvious problems.  But this is manual.

The appveyor image:  Visual Studio 2015, can still be added to the appveyor matrix for testing - which is the testing that you have now anyway.    The difference is that it would first be built on the image: Visual Studio 2022.      

I noted that the VS 2015 image is based on Windows Server 2012 R2, which is itself derived from Windows 8, (Winver 6.2 or even maybe 6.3 Build 9600 from October 11, 2022.    So, I mean, if you really want to be certain it works fine on windows 7, then this is not the ideal test for Windows 7 (technically 6.1 build 7601).  I don't know if appveyor has WIn 7, (readily available) and anyway, as I mentioned, you are already using the Server 2012 R2 based image, so this won't really change anyway.  I'm just being mindful that it will be compiled and built on a platform even further away from the target - which increases the potential gap where risk can occur.



0x0601 // Windows 7

**Comment by zewpo** [comment]
Hi @chrisbra 

Quick update...  

I got the VS 2022 image building vim and the installer properly, which solves this problem of weird characters.   - but - it initially caused some existing testing to start failing.   After pushing and poking things around I found a solution for those failing tests was to drop support for Win XP, and just let the build go with the default WIn 7, which is preset in Vim's makefile.   

Now, since I discovered that it was building to an XP-target that was causing the problem, I'm trying a couple tests to see if we can still use the old VS 2015 image to do the builds - without targeting XP.   If this works, this will mean you have the option to stick with VS 2015, or go with the newer 2022.  So, I'll let you know how that goes.

**Comment by k-takata** [comment]
We can go with 2022.

**Comment by chrisbra** [comment]
I am also in favor of using 2022

**Comment by chrisbra** [comment]
closing, since #296  has been merged
