### ISSUE TITLE
Feature request: VisVim for Visual Studio and "OfficeVim" for Office

### ISSUE THREAD

**Issue by duytrung** [vim/vim-win32-installer#30]
Hi,

I'm after an equivalent VisVim for Office application. There is Viemu but it doesn't work with my Office 2016 and cost ~100USD.

Can I request for a function to integrate VisVim with MS Office? I'm not programming in C/C++ so it is definitely hard for me, provided that Visvim can add function for Word.

Any suggestion?

Thanks!

**Comment by chrisbra** [comment]
that is definitely not the correct forum to request enhancements for Vim. You could use the vim/vim repository, however note that unless someone spends much time and effort implementing it, it will probably be take very long until this gets implemented. There might exist some plugins that let you use vim as external editor, don't know.

**Comment by j16180339887** [comment]
Plugins like VisVim and Viemu are always lacking some functionalities.

So this is what I do:

1. Open vim

2. `:set spell`

3. Edit my drafts

4. Paste it to the office applications
