### ISSUE TITLE
Win32 daily release routines seem stopped

### ISSUE THREAD

**Issue by skywind3000** [vim/vim-win32-installer#307]
### Steps to reproduce

The latest release is from last week.

### Expected behaviour

create the win32 daily build regularly

### Version of Vim

9.0.1300

### Environment

Windows 10

**Comment by davea1** [comment]
Christian released a new build earlier today and he already has new patches in process, so I think this one can be closed.

**Comment by skywind3000** [comment]
I was worry about him, since he hadn't got any activities on github in three weeks.
glad to hear he's back.
