### ISSUE TITLE
[Bug Report] After I close vim for windows, files with ~ appeard

### ISSUE THREAD

**Issue by CoolPlayLin** [vim/vim-win32-installer#309]
### Steps to reproduce

- RUN *vim for windows*

https://github.com/vim/vim-win32-installer/assets/96709586/419f59f1-7ad4-4569-be09-4c01547895f4

### Expected behaviour

- RUN *vim* in *wsl*

https://github.com/vim/vim-win32-installer/assets/96709586/5db075cf-a2f2-4ed6-b149-17f87b34f4c2

### Version of Vim

9.0.1579

### Environment

- Windows OS
![image](https://github.com/vim/vim-win32-installer/assets/96709586/bdd3eea7-9b34-481a-bb4f-69ffe6c634d8)

Installer Package: 64-bit installer

**Comment by k-takata** [comment]
The default .vimrc (`C:\Program Files\Vim\_vimrc`) includes `vimrc_example.vim`, and it sets the `backup' option.
If you don't like it, you can simply create your own .vimrc.
