### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by bitsandscraps** [vim/vim-win32-installer#31]
I have installed python 3.6 on my computer, but
```:python3 print("Hello world")```
returns
```
E370: Could not load library python35.dll
E263: Sorry, this command is disabled, the Python library could not be loaded.
```

Do I need to downgrade Python to version 3.5?

**Comment by chrisbra** [comment]
you might try setting the `pythonthreedll` option to python36.dll. Not sure if python 3.5 and 3.6 are compatible, so this may or may not work and it can possibly crash your vim.

Having said this, supporting python 3.6 instead of 3.5 might be a good idea.

**Comment by k-takata** [comment]
Currently, it is compiled with Python 3.5, so basically Python 3.5 is needed. (No need to uninstall 3.6.)

Changing 'pythonthreedll' to "python36.dll" might also work (but not tested and not recommended).

**Comment by bitsandscraps** [comment]
I have installed Python 3.5, but the error does not disappear. My `python35.dll` is in `C:\Users\bits_and_scraps\AppData\Local\Programs\Python\Python35` and this directory is in the `%PATH%`.

**Comment by k-takata** [comment]
If you use 32-bit Vim, python must be 32-bit.

**Comment by bitsandscraps** [comment]
Thanks. I thought I installed 64-bit version.
