### ISSUE TITLE
Trojaned installer?

### ISSUE THREAD

**Issue by readnotify** [vim/vim-win32-installer#315]
### Steps to reproduce

See https://www.virustotal.com/gui/file/95028171ec0e209b25ec3a7ac2ea515c1f6b4b26f3617a7cdd2ce2221c537fb6

6 different vendors is seriously stretching the likelihood that this is just a false-positive?

The online world is not the safe place it used to be - nasty gangs, nation states, "researchers", script-kiddies and more are subverting everything you can imagine these days.

### Expected behaviour

No virus warnings.  No sketchy operations like this reported:

Security Software DiscoveryT1518.001May try to detect the virtual machine to hinder analysis (VM artifact strings found in memory) Uses the "uname" system call to query kernel version information (possible evasion)

### Version of Vim

v9 installer

### Environment

windows

**Comment by chrisbra** [comment]
You did not mention, what file you uploaded :/

Anyway, this seems to happen fairly often, search the existing issues like this: https://github.com/vim/vim-win32-installer/issues?q=label%3Aanti-virus+

It seems those anti-virus heuristics are way too aggressive and so flag innocent files as suspicious.

It seems to happen quite often with install.exe perhaps it's the use of UPX. Maybe we should get rid of that. 

Anyhow, there doesn't seem to be anything actionable for us here. so closing as anti-virus related.

**Comment by readnotify** [comment]
I scanned a bunch of older gvim's installer I had lying around, and none of them trigger any warnings.
ALL of your new versions do (I tried a bunch)

**Comment by readnotify** [comment]
Yeah, get rid of UPX.  It's the more-responsible action to take.  Even if AL SIX are false-positives, the fact you're distributing so many unsigned versions is a major risk to begin with, and the day someone does trojan your unsinged distro nobody's going to notice that 7th non-false-positive...

Safety is important, even in open-source.  Here's this weeks example of people not taking it seriously: https://www.searchenginejournal.com/massive-leak-of-chatgpt-credentials-over-100000-accounts-affected/489801/

Can you even *imagine* the pain of all those 100000+ developers who now have to disinfect their systems, cancel all their accounts, re-subscribe to everything, and so forth?

**Comment by k-takata** [comment]
@readnotify 
If you think the false positives really matter, could you help reporting to each AV vendor about the false positives?

@chrisbra 
It might be better to create FAQ page in our Wiki...

**Comment by readnotify** [comment]
Something done recently caused these alerts - none of your older versions are doing this.
What makes you think they are all false positives?
I cannot imagine a reason why the installer would need to be rebuilt for version 9 - the clear version 8 installer *should* be identical ?

**Comment by chrisbra** [comment]
the installer is re-built when Vim is built. 

> What makes you think they are all false positives?

Mostly because there haven't been any changes to it, and then there are still like 65 AV vendors that flag it as okay.

**Comment by readnotify** [comment]
One of the huge problems with Open-source and volunteer contributors, is that everyone is anonymous with no accountability, and every country on earth, plus a massive number of malware gangs and "security researchers" and are malicious people are all just a few allegedly "helpful" clicks away from injecting their obfuscated malicious adjustments.

It's really difficult to know, when someone says "do nothing" or "ignore it" or "stick it in the FAQ" etc, whether THAT is one of these malicious people protecting their backdoor, or just someone ignorant about safety.  When the obvious action of "remove UPX" is totally ignored, it raises even more suspicions.

If you don't want to fix the problem, stop responding to this issue.  Leave it up to someone who cares about user safety to make your product safer for people to use.

It does NOBODY any good to lobby for other kinds of actions that don't improve the product.  Even if all 6 of those are wrong (which they might not be - those 6 vendors are telling to to beware for multiple different reasons), it's still worth un-doing whatever you did that caused all those detections.  If any of them are *right*, you've fixed the problem that way.

Just grab an installer.exe from version 8 or whatever and use that.  Solved, and guaranteed to remove whatever sketchy thing appeared in the latest release from wherever it arrived.

**Comment by chrisbra** [comment]
Nothing is ignored,  see https://github.com/vim/vim-win32-installer/pull/316

Now why those AV vendors start flagging the installer I have no idea. They should indicate clearly if they detect an actual problem that we can fix or are just flagging because of some heuristics (which honestly tend to be over aggressive and just cause more pain than being helpful, see the various projects that have to cope which this, e.g. git for windows, nsis installer, etc). 

Usually it's more the later case, in which case the projects can't do anything against it but have to live with it.

**Comment by k-takata** [comment]
> See https://www.virustotal.com/gui/file/95028171ec0e209b25ec3a7ac2ea515c1f6b4b26f3617a7cdd2ce2221c537fb6

It seems that installer.exe is warned, however, installer.exe itself is not packed by UPX.
UPX is used to pack the executable file generated by NSIS. So, UPX is not related in this case.
