### ISSUE TITLE
Tcl DLL name is wrong

### ISSUE THREAD

**Issue by k-takata** [vim/vim-win32-installer#32]
Since ActiveTcl 8.6.6, the DLL name had been changed from `tcl86.dll` to `tcl86t.dll`.
Vim 8.0.0989 supports the `TCL_DLL` compile option to set the DLL name.
See also: https://groups.google.com/d/msg/vim_dev/-66BRdu3Yx0/xbxozWVZAgAJ

However I'm not using the option now. When I tried to set it, if_tcl couldn't find the DLL on my AppVeyor account.
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/93/job/mw6tg69qf8lxvs6w#L966
This is really strange, because tcl86t.dll does exist in the $PATH:
https://ci.appveyor.com/project/k-takata/vim-win32-installer/build/93/job/mw6tg69qf8lxvs6w#L831

Possible options might be:

1. Find the cause and fix it. Use `TCL_DLL=tcl86t.dll` setting.
   Seems difficult.
2. Use `TCL_DLL=tcl86t.dll` setting. Skip tests for if_tcl.
   Users can use a DLL from ActiveTcl 8.6.6, but it is not tested.
3. Keep current setting (`TCL_DLL=tcl86.dll`). Don't skip tests for if_tcl.
   Users should use a DLL from ActiveTcl 8.6.4 or earlier, or one from MinGW.

**Comment by k-takata** [comment]
Bram has been already set `TCL_DLL=tcl86t.dll` in [bigvim.bat](https://github.com/vim/vim/blob/4f1982800f0aff28df6875e718a786f6c4b11ad9/src/bigvim.bat).
I think we should follow it (even if the test for if_tcl doesn't work on AppVeyor).

**Comment by chrisbra** [comment]
agreed.

**Comment by k-takata** [comment]
I haven't still found the cause of this problem, but I found a workaround for this.
It looks that copying the Tcl DLL to the current directory and setting $TCL_LIBRARY works.
