### ISSUE TITLE
Key mapping of upper-case wide char needs pressing Shift (gVim/Windows)

### ISSUE THREAD

**Issue by xavier-gl71** [vim/vim-win32-installer#323]
### Steps to reproduce

With gVim only.

`:imap É Eacute`
Switch to insert mode.
Pressing `É` (Shift+`é`) inserts "É".
Press `CapsLock`.
Pressing `É` (without Shift) inserts "Eacute".

Note: Bépo keyboard layout. Same issue with other chars ( Ç, À, …)

### Expected behaviour

Pressing `É` (Shift+`é`) should insert "Eacute" (without capslock).

vim.exe in a terminal is ok.
gvim v8.2.4803 is ok
gvim v8.2.4815 is broken

Maybe [this patch](https://github.com/vim/vim/commit/77fc0b02e53bdc49213900e0055cb6d678ce180d) ?

### Version of Vim

From 8.2.4815 to 9.0.1922

### Environment

Windows 11 64bits
gVim 32bits

**Comment by chrisbra** [comment]
This belongs to the vim repository, not here. Please see the vim PR at https://github.com/vim/vim/pull/12752 (note you may want to check and verify its behaviour there) and linked issues there.
