### ISSUE TITLE
The Vim Windows installer is compromised!

### ISSUE THREAD

**Issue by zmajeed** [vim/vim-win32-installer#324]
### Steps to reproduce

Recent Vim Windows installers at https://github.com/vim/vim-win32-installer contain malicious trojans - but the installer maintainer keeps ignoring antivirus reports - https://github.com/vim/vim-win32-installer/issues?q=is%3Aissue+trojan

The latest signed installer gvim_9.0.1916_x64_signed.exe was quarantined by Windows Security

```
Threat Quarantined - Severe
Detected: Trojan:Script/Wacatac.B!ml
Status: Quarantined
Quarantined files are in a restricted are where they can't harm your device. They will be removed automatically
Date: 9/21/2023 4:22 PM
Details: This program is dangerous and executes commands from an attacker.
Affected Items:
file: C:\tmp\vim90\install.exe
```

### Expected behaviour

Virus-free secure installer

### Version of Vim

v9.0.1916

### Environment

Windows 11

**Comment by chrisbra** [comment]
We are not ignoring those. You can check the installer at virustotal, this is a false-positive and you need to complain to your anti-virus provider. There is nothing we can do here. See also the discussions at related issues: https://github.com/vim/vim-win32-installer/issues?q=is%3Aissue+is%3Aclosed+label%3Aanti-virus

I am closing this.

Thanks for understanding.

**Comment by chrisbra** [comment]
For the record: I checked the file using virustotal:
https://www.virustotal.com/gui/url/ae3b3b023769a96671ae883887f1d70887bca75eacdc66a6db03c17650524271?nocache=1

Oh and apparently one can mark a file as false-positive here: https://www.microsoft.com/en-us/wdsi/filesubmission 
(It requires a microsoft account and I do not have one except for my professional one, which I don't want to use for obvious reasons).

**Comment by k-takata** [comment]
I'm thinking whether we should create an FAQ page about this in the [Wiki page](https://github.com/vim/vim-win32-installer/wiki).

**Comment by chrisbra** [comment]
yeah, right: https://github.com/vim/vim-win32-installer/wiki#the-installer-contains-a-virustrojanermalware-what-should-i-do

**Comment by chrisbra** [comment]
also update the issue template
