### ISSUE TITLE
Error uploading artifact to the storage: Remote server returned 503: Service Unavailable

### ISSUE THREAD

**Issue by skywind3000** [vim/vim-win32-installer#332]
### Steps to reproduce

![图片](https://github.com/vim/vim-win32-installer/assets/3035071/e3225896-f497-484d-9fd9-867eee1f7b3f)

https://ci.appveyor.com/project/chrisbra/vim-win32-installer/builds/49243934/job/5x5n7pw5r6ljqhy7

### Expected behaviour

the release binary files can get uploaded

### Version of Vim

9.1.125

### Environment

Windows 10

**Comment by chrisbra** [comment]
Well, this seems like a github failure. There is nothing we can do to fix those.

**Comment by skywind3000** [comment]
can't wait to try the latest `getregion()` function, 
but I don't have the right environment to build my self.
