### ISSUE TITLE
Could not load library libsodium.dll

### ISSUE THREAD

**Issue by VimWei** [vim/vim-win32-installer#337]
### Steps to reproduce

1. Open gVim
2. `<Leader>c ` to change colorsheme

```
noremap <silent> <leader>c :call RandomColorScheme()<cr>:color<cr>
let s:last_colorscheme_cmd = ''
function! RandomColorScheme()
    let l:colorscheme_cmds = [
        \ 'ColorLucius',
        \ 'ColorGruvbox8',
        \ 'ColorSolarized8',
        \ 'ColorLandscape',
        \ 'ColorMaterial',
        \ 'ColorPaperColor',
        \ 'ColorSonokai',
        \ 'ColorHybrid',
        \ 'ColorNord',
        \ 'ColorOne',
    \ ]
    let l:random_index = rand() % len(l:colorscheme_cmds)
    while l:colorscheme_cmds[l:random_index] == s:last_colorscheme_cmd
        let l:random_index = rand() % len(l:colorscheme_cmds)
    endwhile
    let l:random_color_cmd = l:colorscheme_cmds[l:random_index]
    let s:last_colorscheme_cmd = l:random_color_cmd
    execute l:random_color_cmd
endfunction
```
3. Error:
![image](https://github.com/vim/vim-win32-installer/assets/25874852/1e78572b-899a-4c84-a317-8fe8f12fd741)

### Expected behaviour

Random colorscheme

### Version of Vim

gvim_9.1.0252_x64_signed

### Environment

Version: Windows 10 Pro
Version Number: 22H2
OS Build: 19045.4170
Experience: Windows Feature Experience Pack 1000.19054.1000.0

**Comment by VimWei** [comment]
Addition: gvim_9.1.0165_x64_signed.exe has not this issue.

ref: https://github.com/vim/vim-win32-installer/issues/220

**Comment by chrisbra** [comment]
Missing information. Where did you install it? Did you use the installer? Is the library there?

**Comment by VimWei** [comment]
I use gvim installer gvim_9.1.0252_x64_signed.exe.  

I have not separately installed the library libsodium.dll; this is the first time I've encountered this. I previously used gvim_9.1.0165_x64_signed.exe without this issue, but after upgrading to the latest gvim_9.1.0252_x64_signed.exe, this problem arose.

**Comment by chrisbra** [comment]
so can you please check inside your location if the library is there? What is the location of the installation directory?

**Comment by VimWei** [comment]
Every option in installer is default.    
The location of the installation directory:  `c:\Program Files\Vim\vim91\`

I searched the entire hard drive and only found：

![image](https://github.com/vim/vim-win32-installer/assets/25874852/3527d656-a3d4-4906-8b6c-f3f8c2110c90)

**Comment by VimWei** [comment]
If gvim_9.1.0165_x64_signed.exe is installed, then this file exists here.

![image](https://github.com/vim/vim-win32-installer/assets/25874852/7f86edfe-a7c9-4dd6-ba08-d245edcc9b88)

**Comment by chrisbra** [comment]
It seems like we lost the libsodium and a few other libraries
![image](https://github.com/vim/vim-win32-installer/assets/244927/1f9bd943-4263-4d41-94f8-de7369d2514b)

**Comment by chrisbra** [comment]
for now you can manually copy the libraries from the zip archive over.

**Comment by k-takata** [comment]
It seems that v9.1.0191 broke this.

**Comment by k-takata** [comment]
https://github.com/vim/vim/commit/2680a074d4790abb372ecda658b0c455a6fe06cf

```
!if /FileExists "${VIMRT}\libsodium.dll"
	File ${VIMRT}\libsodium.dll
!endif
```
was changed to:
```
!if /FileExists "${VIMTOOLS}\libsodium.dll"
	File ${VIMTOOLS}\libsodium.dll
!endif
```
`gvim.nsi` or `appveyor.bat` should be modified.

**Comment by chrisbra** [comment]
yep I noticed. It was done intentionally, as mentioned in the PR. @RestorerZ can you please have a look?

**Comment by chrisbra** [comment]
I checked it with https://github.com/vim/vim-win32-installer/releases/tag/v9.1.0271 , libsodium.dll is included again.
