### ISSUE TITLE
Build vim with Python 3.6 support

### ISSUE THREAD

**Issue by branchus** [vim/vim-win32-installer#34]
Hi

Python 3.6 has been around for a while. is it possible to build vim with python 3.6 please?

just a suggestion.

Thanks

**Comment by chrisbra** [comment]
should be possible, just changing this line:
https://github.com/vim/vim-win32-installer/blob/3c9caed46fa3c56410800c9e2f77a8c2c87eeb39/appveyor.bat#L33
to 
```dosbatch
set PYTHON3_VER=36
```

**Comment by branchus** [comment]
Thank you for your quick response and instruction. I didn't make it clear. I mean is it possible that your build of Vim to support Python 3.6 in the near future? Thanks

**Comment by k-takata** [comment]
We can update the python version by changing the line, however Bram still uses Python 3.5 in his official build as we can see it in [bigvim.bat](https://github.com/vim/vim/blob/4f1982800f0aff28df6875e718a786f6c4b11ad9/src/bigvim.bat). I think it's better to keep the nightly builds in sync with bigvim.bat.
(Oh, Bram has been already updated Racket to 6.10. I think we should follow it.)

As it is written in #31, using Python 3.6 might be possible by doing `:set pythonthreedll=python36.dll`, but it is not tested at all.

**Comment by branchus** [comment]
I see
Thank you very much :)
