### ISSUE TITLE
Windows binaries from 9.1.408 package have version 9.1.409

### ISSUE THREAD

**Issue by chrullrich** [vim/vim-win32-installer#340]
### Steps to reproduce

1. Download https://github.com/vim/vim-win32-installer/releases/download/v9.1.0408/gvim_9.1.0408_x64.zip
2. Look at the version details of `gvim.exe`

### Expected behaviour

The file and product versions should be 9.1.0408. Instead they are 9.1.0409.

### Version of Vim

9.1.408

### Environment

n/a

**Comment by chrisbra** [comment]
Yep, it seems we imported and tagged only v9.1.408 in master and by the time the build process run, I had already pushed up 9.1.409 on the vim repo: https://github.com/vim/vim/commit/82792db6315f7c7b0e299cdde1566f2932a463f8 which then got pulled into the repo here when releasing: https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/70tfne8l1pwgaf6x?fullLog=true#L21

Well, that is unfortunate, but I cannot change this anymore.

**Comment by chrisbra** [comment]
I am closing this, as I am not sure there is any actionable here to be done. I'll try not to push new commits to the main repo after midnight (when this repo here does the daily release) to prevent this in the future.

**Comment by chrullrich** [comment]
I assumed the build was made from the current state of the vim submodule over here, not least because that is apparently updated every time. I'm not familiar with how the build process works, or the intricacies of Git submodules, but wouldn't it be a good fix to use that instead of taking the code up to the HEAD of vim/vim as apparently happened here?

Looking at the build log, ISTM that removing the `git submodule update --remote` command would have just that effect. But I'm guessing here.
