### ISSUE TITLE
Input key combinations (for mappings) are no longer detected

### ISSUE THREAD

**Issue by terminatorul** [vim/vim-win32-installer#341]
### Steps to reproduce

" Install latest x86_64 version (64-bit), currently gvim_9.1.0443_x64.exe
```
  nmap <C-1> 1<C-W>w
" nmap <C-2> appears to work...
  nmap <C-3> 3<C-W>w
  nmap <C-4> 4<C-W>w
```

I use such maps to move the caret to various windows I have open

press one of the mappings &lt;C-1&gt;

mapping is not triggered

### Expected behaviour

For the official binary version (form vim.org), also 64-bit, the mapping works fine.
On Linux (openSUSE Tumbleweed up-to-date) the mapping also works fine

### Version of Vim

gvim_9.1.0443_x64.exe (lastest available)

### Environment

Windows 10, 64-bit package

**Comment by terminatorul** [comment]
I built vim on Windows by following the INSTALLpc.txt file, and I find that when I enable DIRECTX=yes on the `nmake` command line, the keyboard mappings do not work

If I do not use `DIRECTX=yes`, the mappings work as expected

Also, my keboard layout in Windows Settings (the "default input method" as it is called now) is Romanian (Legacy)

**Comment by terminatorul** [comment]
I built Vim from source from the master branch, with all interfaces and options described in the makefile and in the build instructions, except for MZSCHEME which does not work any more with the latest version of the language (Racket 8.13).

I have exactly the same problem after building GUI version of Vim. Console version of Vim detects the input key combinations <C-1>, <C-3>, <C-4>, ... as expected. Notice <C-2> somehow just works all the time.

For the GUI version I tried building with DIRECTX=no and IME=no, with no effect. GUI Vim still can not detect the input key combinations.

My keyboard layout in Windows settings (the "default input method" as it is called now) is Romanian (Legacy)

**Comment by terminatorul** [comment]
If I use Ctrl+Q in insert mode, trying to input a literal control character, nothing hapens when I input &lt;C-1&gt;, &lt;C-3&gt;, &lt;C-4&gt; ... there is no input

**Comment by k-takata** [comment]
Please check `:help w32-experimental-keycode-trans-strategy`.

**Comment by terminatorul** [comment]
Oh, thank you !

My Vim installation does not have this help topic (I installed the official 64-bit Vim 9.1.000 package), but I found it on vimhelp.org.

The recommended snippet also did not work with the Vim version I built from source:
```Vim
:call test_mswin_event('set_keycode_trans_strategy', {'strategy': 'experimental'})
```
but the alternative version using the environment variable did the trick:
```bat
Set VIM_KEYCODE_TRANS_STRATEGY=experimental
```

Can I enable this at build time please ?

**Comment by terminatorul** [comment]
It appears I can set the environment variable in my `_vimrc` file as well:
```Vim
let $VIM_KEYCODE_TRANS_STRATEGY = 'experimental'
```
