### ISSUE TITLE
request: add patchlevel to the version registered in the windows registry

### ISSUE THREAD

**Issue by hexcoder-** [vim/vim-win32-installer#359]
Also see the twin issue in https://github.com/vim/vim/issues/15990

**Problem**
In my company installed software (eg vim) is scanned regularly. For the installed version of each software component a lookup with known vulnerabilities is done, and in case of any findings the user is urged to update.

For version 9.1.0000 there were 4 known CVEs, that were fixed soon afterwards (thanks!).
When I upgraded to the latest vim version the following scans kept reporting those 4 CVEs, since the windows registry only names 9.1 as the vim version, but not eg 9.1.0837.
So the scanner is not able to differentiate between the fixed and the vulnerable version. Of course the scanning is automated and will mercilessly escalate this (informing my boss about it).

**Describe the solution you'd like**
If the release policy could be changed to increase the minor version after fixing of CVEs, that would very certainly help.

**Alternative**
If the installer could be changed to put the patchlevel part also in the version as seen in the registry, that maybe might help.

Thanks!

**Comment by chrisbra** [comment]
Each change in the Vim C source code increments the patch number and so we have a new version. And the patchlevel is already part inside the Registry: 
![image](https://github.com/user-attachments/assets/c301714e-7c95-4a2a-adca-29170d6a0c4f)
![image](https://github.com/user-attachments/assets/c1e97f0e-6d75-4f8f-9d4d-10ecf89f852d)

**Comment by hexcoder-** [comment]
Thanks, but on my laptop it looks like this:
![image](https://github.com/user-attachments/assets/79784c1e-bbdc-4590-af8c-b5b98870fa1d)

**Comment by chrisbra** [comment]
That is strange , it should have been installed in `c:\Program Files` and not under `c:\Program Files(x86)` Can you please uninstall and make sure you have no other version installed in `c:\Program Files` or `c:\Program Files (x86)`? And then try again?

**Comment by hexcoder-** [comment]
There were no other places where vim had been installed. I uninstalled and then reinstalled, now it does not show up as installed anymore. Whatever, my initial problem seems to have vanished. Closing this issue.
