### ISSUE TITLE
Windows Defender: Trojan:Win32/Fuerboos.A!cl found in gvim_8.0.1216_x86.exe

### ISSUE THREAD

**Issue by vhaasteren** [vim/vim-win32-installer#36]
When downloading the executable of gvim 8.0, Windows Defender finds a trojan: Trojan:Win32/Fuerboos.A!cl

The file is: gvim_8.0.1216_x86.exe

**Comment by k-takata** [comment]
I download it on Windows 10, but Windows Defender didn't warn it. Does it still occur?

It seems that we can submit a file for analysis from here:
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by vhaasteren** [comment]
Yep, the warning is still there. I have done the Microsoft Defender file submission, so they will take a look at it. I'll keep you posted.

**Comment by vhaasteren** [comment]
As expected, the submission was completed and the verdict for gvim_8.0.1216_x86.exe is: "not malware".

I guess that's that. Hope they update their definitions soon (I have 1.255.118.0). Current status on updating is 'pending', both for cloud and client.

**Comment by chrisbra** [comment]
I a closing this, as this is not really a problem caused by anything we have under our control here. Thanks.
