### ISSUE TITLE
x64 bit exe support?

### ISSUE THREAD

**Issue by jungle-boogie** [vim/vim-win32-installer#39]
Hello,

Thanks for publishing the windows builds of vim so frequently. Having gvim/vim on windows is a nice treat.

is it possible to provide x64 bit exe files for the nightly builds? It looks like the x86 exe builds are provided:
https://github.com/vim/vim-win32-installer/releases/tag/v8.0.1322

Thanks for the consideration!

j.b.

**Comment by k-takata** [comment]
Currently, the installer script (gvim.nsi) doesn't support building 64-bit installer exe files.
It is because Bram thinks that 32-bit exe is enough for most use cases:
https://github.com/vim/vim/blob/a2a80162deb1e96e16b097dfe48b61b6eb0824bf/src/INSTALLpc.txt#L18-L20

**Comment by jungle-boogie** [comment]
Well Bram's comment is valid - 2GB files can be edited with x64 vim.

**Comment by k-takata** [comment]
Actually 32-bit Vim can also edit > 2 GB files if 'swapfile' is enabled. It is very slow, though.
Do you need to edit such a large file?

**Comment by jungle-boogie** [comment]
hi @k-takata, no, I don't currently have the need.

**Comment by chrisbra** [comment]
It is currently not apparent, that there is actually a need for a 64bit installer. We might reconsider in the future however. Closing therefore.
