### ISSUE TITLE
Python 3 - upgrade to 3.6.x

### ISSUE THREAD

**Issue by jungle-boogie** [vim/vim-win32-installer#40]
Hello,

Would it be possible to bump up the version of python supported in vim for windows?
`-DDYNAMIC_PYTHON3_DLL=\"python35.dll\"`

The latest python is 3.6.3:
https://www.python.org/downloads/release/python-363/

> Python 3.5.4 is the last "bugfix" release of 3.5. The Python 3.5 branch has now entered "security fixes only" mode; going forward, the only improvements made in the 3.5 branch will be security fixes.

https://www.python.org/downloads/release/python-354/

**Comment by k-takata** [comment]
I created a PR to the vim/vim repository. (vim/vim#2429)
I will update this repository after it is merged.

**Comment by jungle-boogie** [comment]
My `:version` still shows this:

`-DDYNAMIC_PYTHON3_DLL=\"python35.dll\"`


```
>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 10 2017 23:07:26)`

**Comment by chrisbra** [comment]
I suppose vim/vim#2432 fixes that.

**Comment by jungle-boogie** [comment]
Ah, cool. Once that's approved and merged, I'll see if it's correct in vim 32bit exe.

**Comment by k-takata** [comment]
Please try https://github.com/vim/vim-win32-installer/releases/tag/v8.0.1387 .

**Comment by jungle-boogie** [comment]
Good now!

` -DDYNAMIC_PYTHON3_DLL=\"python36.dll\"`

Thanks for the extra hard work on upgrading to python36!
