### ISSUE TITLE
The latest installer contains the trojan Win32/Fuerboos.C!cl

### ISSUE THREAD

**Issue by clarkezone** [vim/vim-win32-installer#42]
Seems kinda bad:
![image](https://user-images.githubusercontent.com/1128250/33852571-e85b51c4-de6f-11e7-8073-be35aa3c2a87.png)

**Comment by mzlogin** [comment]
1401 contains another, Trojan:Win32/Fuery.A!cl

![image](https://user-images.githubusercontent.com/1646590/34097209-422e9f28-e413-11e7-9e3e-6a9e0ffa63fc.png)

**Comment by k-takata** [comment]
Sorry, I don't have time for this now.
Can anyone submit the file(s) for analysis to Microsoft? See https://github.com/vim/vim-win32-installer/issues/36#issuecomment-339816077 for detail.

**Comment by chrisbra** [comment]
please submit to MS as per the last comment. Nothing we can fix here. Closing.
