### ISSUE TITLE
Fail to load a proper Ruby DLL

### ISSUE THREAD

**Issue by bohrshaw** [vim/vim-win32-installer#43]
The `:ruby 2` command fails with `E370` and `E266` in my setup.

* My ruby DLL is present in `$PATH` and its name matches `&rubydll`.
* `set rubydll=C:\Ruby24-x64\bin\x64-msvcrt-ruby240.dll` still fails.

I am confused what goes wrong.

**Comment by k-takata** [comment]
Do you use 64-bit version of Vim?
Then, please also add `C:\Ruby24-x64\bin\ruby_builtin_dlls` to your `$PATH`.

**Comment by bohrshaw** [comment]
Thanks! My vim is 64-bit and now it works.
