### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by UnitedMarsupials** [vim/vim-win32-installer#44]
Symantec on my machine quarantined the install -- the `gvim_8.0.1417.exe` executable -- because of the `SONAR.PSDownloader!g1` in it.

![image](https://user-images.githubusercontent.com/1486340/34226325-546f6e62-e597-11e7-9dda-862627076e34.png)

**Comment by k-takata** [comment]
Could you report it to Symantec?
Cf. #36, #42

**Comment by giupino82** [comment]
Hi all, 
i've submitted the file to symantec, this is their response:

-----------------------------------------------------------
Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: gvim_8.0.1427_x86.exe
    MD5: c4e505058fde14de8da08b7ec16001b0
    SHA256: 5c303d30181f3b7e61b9c8368fc862f9e93035d28e7e5cc5bc5c335a465cf51e
    Note: Whitelisting may take up to 24 hours to take effect via Live Update

If detection persists, please contact support:
* Norton: https://support.norton.com/sp/en/us/home/current/info
* SEP: https://support.symantec.com/en_US/endpoint-protection.54619.html

Decisions made by Symantec are subject to change if alterations to the Software are made over time or as classification criteria and/or the policy employed by Symantec changes over time to address the evolving landscape.
------------------------------------------------------------------------------

**Comment by CNMan** [comment]
quarantine
![2018-01-01_233120](https://user-images.githubusercontent.com/8692234/34468819-e9f639c6-ef4b-11e7-8347-59e2d25ed84e.png)

**Comment by chrisbra** [comment]
if this happens, contact your AV vendor to have the files check again/whitelist. Closing this, as this is nothing we can influence here.
