### ISSUE TITLE
“LANG” “language messages”parameter does not work

### ISSUE THREAD

**Issue by HeJiaJunPan** [vim/vim-win32-installer#45]
gvim8 Windows10_64 chinese
in _vimrc,
```
let $LANG = 'en_US.UTF-8'
```
or
```
language messages en
```
message is still chinese

**Comment by chrisbra** [comment]
> let $LANG = 'en_US.UTF-8'

this would not work on Windows, as Windows does not use the LANG environment variable.

What archive did you use? How do you know the message is still chinese? Do you have the lang folder below vim/vim80/?

I just downloaded https://github.com/vim/vim-win32-installer/releases/download/v8.0.1427/gvim_8.0.1427_x64.zip extracted it run gvim.exe and could successfully change the language using `:lang fr` for french or `:lang de` for using the german language.

**Comment by HeJiaJunPan** [comment]
thank you
