### ISSUE TITLE
Update diff.exe?

### ISSUE THREAD

**Issue by geraldcombs** [vim/vim-win32-installer#46]
The diff.exe in the top-level directory in this repository says it's version 2.7:
```
>.\diff.exe --version
diff - GNU diffutils version 2.7
```
According to http://git.savannah.gnu.org/cgit/diffutils.git/tag/?h=v2.7 that version was released in 1994. Would it be possible to upgrade to a more recent version? I ran into this when trying to run a script that depends on `--strip-trailing-cr` on a system that had Vim's `diff` first in its path.

Alternatively you might consider placing utility programs in a separate, out-of-%PATH% directory similar to what Git for Windows does.

**Comment by chrisbra** [comment]
@brammool 
I guess this is more an issue that Bram should comment on, as this might have an impact on current Vim source (e.g. where Vim expects diff.exe to be)

**Comment by brammool** [comment]
What version do you suggest we replace it with?  Note that it must be build in a way that it runs almost everywhere (no dependencies on specific dlls).

I'm still hoping someone will pick up the project to have the diff functionality internally, it would greatly improve the speed and accuracy.

**Comment by chrisbra** [comment]
that would make a good GSOC project :)

**Comment by geraldcombs** [comment]
For my purposes, any version that supports `--strip-trailing-cr` would be preferred. [MSYS2](http://www.msys2.org/) currently provides diffutils 3.5, which is more than sufficient. It's not static (it depends on msys-2.0.dll, msys-gcc_s-1.dll, msys-iconv-2.dll, and msys-intl-8.dll) but it is self-contained in a way that binaries built against, say, cygwin1.dll and the various Visual C++ runtimes aren't.

**Comment by chrisbra** [comment]
Note that starting from 8.1.0360 Vim comes with its own diff library. So you can remove the external diff that comes with Vim. (or move Vims diff.exe further down in your PATH variable). In addition, Vim should be able to parse a unified diff format (should have zero context lines). So you can use whathever diff you need with a custom diffexpr setting.

**Comment by okhowang** [comment]
> Note that starting from 8.1.0360 Vim comes with its own diff library. So you can remove the external diff that comes with Vim.
so can we remove diff.exe from installer?
it break some other tools for example [goimports](https://github.com/golangci/golangci-lint/issues/1169#issuecomment-800782064)

**Comment by chrisbra** [comment]
I am not sure how this relates. If you need an external diff tool, you should rather install it directly and not depend on a project that used to include it as well. MSYS2 should work. Or git for windows. Or mingw. There are enough options.
