### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by FR4N7Z** [vim/vim-win32-installer#47]
Hello,
When I tried to use a plugin where ruby is needed, the launch fail.
Moreovor when I run :echo has('ruby') the answer is 0.
Is ruby supported whith this release?

Thanks a lot

**Comment by k-takata** [comment]
Could you try adding `C:\Ruby24\bin` and also `C:\Ruby24\bin\ruby_builtin_dlls` to the `PATH` environment? (If you use 64-bit Vim, replace `Ruby24` with `Ruby24-x64`.)

**Comment by k-takata** [comment]
I think this is a duplicate of #43.

**Comment by FR4N7Z** [comment]
Adding C:\Ruby24\bin\ruby_builtin_dlls to the PATH solved the issue.
Thank you.
