### ISSUE TITLE
E370: Could not load library python36.dll

### ISSUE THREAD

**Issue by FR4N7Z** [vim/vim-win32-installer#48]
Hello,
I am using the lasversion of vim with dynamic support of python 3.
When I run :version, Vim is looking for Python36.DLL.
Python3 is installed in C:\Program Files (x86)\Python36-32, the DLL is in this folder and this folder is in the PATH. But when I run :python3 print("Hello world"), it returns 
E370: Could not load library python36.dll
E263: Sorry this command is disabled, the Python library could not be loaded.
Thank you.

**Comment by k-takata** [comment]
What does `:echo system('where python36.dll')` show?

**Comment by FR4N7Z** [comment]
It say in French that it is impossible to find files for the model

**Comment by k-takata** [comment]
Then the PATH setting might be something wrong?
What does `:echo $PATH` show?

**Comment by FR4N7Z** [comment]
The path show C:\Program Files (x86)\Python36-32\ where is python36.dll.

**Comment by i-give-up** [comment]
If you try to run `python` on cmd.exe or powershell, does it start the python interpreter with some text like this?

``` lang-none
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by FR4N7Z** [comment]
Yes it show a message like this.
And yes Vim is 32 bits.
Thank you.

**Comment by i-give-up** [comment]
That's very odd. If the dll is in any directory in `$PATH`, Vim should be able to find it. Just tested it myself too.

There's one more thing to try: run this in Vim (replace `\path\to` with your actual directory).

```
:let &pythonthreedll = 'C:\path\to\python36.dll'
```

**Comment by FR4N7Z** [comment]
That's work! I think this is a bug but  your trick works. Thank you.

**Comment by dhvalden** [comment]
I had the same problem for some reason. This is the only solution I've found so far. Thanks a lot!!!

**Comment by chrisbra** [comment]
I am closing this.
