### ISSUE TITLE
Silent install of vim not so silent

### ISSUE THREAD

**Issue by ScriptMyJob** [vim/vim-win32-installer#49]
Hello,

While writing some automation around installing vim on a couple hundred machines I noted that the `/S` argument is not that silent.  I have also tried `/VERYSILENT`.

Specifically, how can I prevent this dialog box from popping up?

![screen-shot-2018-02-28-at-3 22 00-pm](https://user-images.githubusercontent.com/18185488/36813766-3bcf6ffc-1c9b-11e8-8502-ae35fa855e76.png)

While this box is open the installer does not finish.

Respectfully,
Robert J.

**Comment by ScriptMyJob** [comment]
Also is it possible to not add the menu extensions via arguments or will that have to be an after the fact registry edit?

I should also point out that I attempted `/?` to get a list of arguments to no avail.

Thanks in advance for any information!

**Comment by jcasale** [comment]
I have never liked the executable or manual installation processes either, that's why I wrote a trivial [MSI](https://github.com/jcasale/vim-msi) for the distribution. I intentionally avoided using real custom actions for the text manipulation so anyone could build it. Possibly it might help?

**Comment by k-takata** [comment]
A new experimental installer is now available:
https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0454
`gvim_8.1.****_x86-mui2.exe` should now support `/S`. (It doesn't kick the uninstaller silently, though.)

**Comment by k-takata** [comment]
The MUI2 installer has been merged as v8.1.0616. Closing.
