### ISSUE TITLE
Mal/Generic-S detected by anti-virus software Sophos

### ISSUE THREAD

**Issue by rjiang9** [vim/vim-win32-installer#50]
I installed v8.0.1617 on my win7 and Sophos reported Mal/Generic-S' detected. 
![image 010](https://user-images.githubusercontent.com/7293118/37666437-25e2166a-2c25-11e8-973b-610ddb6e2e92.png)

**Comment by chrisbra** [comment]
duplicate of #44  please report to your AV vendor.

**Comment by Unixware** [comment]
same on win10, sure guys your build server is not infected?

**Comment by chrisbra** [comment]
I just uploaded to virustotal:
https://www.virustotal.com/en/file/c87faf9bee4daf774395c0e70546cda25b4f6ccddcb6084eb7fd36636da6ad23/analysis/1521758400/

**Comment by chrisbra** [comment]
Tried again with the exe installer:
https://www.virustotal.com/#/url/d9f3adfcde5f02ab85d982b6f84c2f1909b75b656cfcef03f0a618178456baea/detection

No virus detected. So please report to your AV vendor and have it whitelisted. There is nothing we can do about it.

**Comment by Unixware** [comment]
better fix this dammit "uninstall-gui.exe"

**Comment by chrisbra** [comment]
what are you talking about?

**Comment by k-takata** [comment]
uninstall-gui.exe is automatically generated when you install Vim.
Anyway, please report to your anti-virus vendor.
