### ISSUE TITLE
blank menubar

### ISSUE THREAD

**Issue by sailfish009** [vim/vim-win32-installer#51]
Hi, no menubar shown in gvim, just blank white rectangle.
i tried almost every vim installer from vim.org, they are all same blank.
my pc environment is win7 64bit.

**Comment by k-takata** [comment]
Does it occur when you execute gvim with `gvim -N -u NONE -U NONE`?
Do you use .zip package or self-installer .exe?

**Comment by sailfish009** [comment]
Sorry for late, i ran following line, still same blank( no menubar).

`C:\vim\vim80>gvim -N -u NONE -U NONE

i tried *.zip or *.exe from https://www.vim.org/download.php#pc, all same blank.

i had installed gvim80-586.exe, on my other win7 64bit pc, which works fine.

**Comment by chrisbra** [comment]
I am not sure I understand. Can you post a screenshot please? Also after `:gvim -N -u NONE -U NONE` what is the output of `:scriptnames`? What is your locale set to (`:echo v:lang.'-'.&langmenu`?) Do you have c:\vim\vim80\menu.vim?

**Comment by sailfish009** [comment]
@chrisbra 

here is vim screenshot: https://pasteboard.co/HdWNC9P.png

as you can see, i have "menu.vim".

**Comment by chrisbra** [comment]
what was the output of `:scriptnames`?

**Comment by sailfish009** [comment]
no output

**Comment by chrisbra** [comment]
strange. it is not loading the menu.vim file. And what is the output of `:verbose :set go? `

**Comment by sailfish009** [comment]
>   guioptions=egmrLtT

**Comment by k-takata** [comment]
What is the output of `:echo $VIMRUNTIME`?

**Comment by sailfish009** [comment]
i think we have found that reason: 

> c:\Neovim/share/nvim/runtime

**Comment by chrisbra** [comment]
did you explicitly set that one?

**Comment by chrisbra** [comment]
Is that set as explicit environment variable?

**Comment by sailfish009** [comment]
where should i have to look?

**Comment by sailfish009** [comment]
found that in regedit! deleted it.

**Comment by chrisbra** [comment]
in a cmd.com run: `set |findstr VIMRUNTIME`

**Comment by chrisbra** [comment]
BTW: if neovim installation sets this system wide, it is a bug.

**Comment by chrisbra** [comment]
cc @justinmk

**Comment by sailfish009** [comment]
after rebooting pc, finally it shows menubar!.
