### ISSUE TITLE
Source code (v8.0.nnnn.zip and v8.0.nnnn.tar.gz) does not contain the Vim source code.

### ISSUE THREAD

**Issue by h-east** [vim/vim-win32-installer#52]
The Vim directory after archive extraction is empty.

**Comment by chrisbra** [comment]
I suppose this is because vim is a submodule inside this repository.

**Comment by k-takata** [comment]
Those links are automatically created by GitHub, and I think there's nothing we can do for it. There are no settings to include submodules into the archives.

**Comment by h-east** [comment]
I see.
Since those archives do not contain the source code, I think that linking does not make sense.
In fact, I was expecting that those contained source code.
Is it possible to get rid of those links?

**Comment by chrisbra** [comment]
> Is it possible to get rid of those links?

What links?

**Comment by h-east** [comment]
> What links?

Link to source code archives.
In the case of the latest version (8.0.1780), it is the part surrounded by the following red pen.
Because I think that it is a meaningless archives if it does not contain the source code.

![link](https://user-images.githubusercontent.com/518808/39464513-d9cbb1e6-4d58-11e8-8922-2307b23df47e.png)

**Comment by k-takata** [comment]
> What links?

I think that the links in the GitHub Releases page (e.g. "Source code (zip)" and "Source code (tar.gz)" are exist in https://github.com/vim/vim-win32-installer/releases/tag/v8.0.1780), and as I wrote there are no such settings.

**Comment by k-takata** [comment]
There is nothing we can do for this, so closing.
(Or please ask to GitHub support.)
