### ISSUE TITLE
Seeing a Command Prompt box flash quickly on Windows 10？

### ISSUE THREAD

**Issue by TeYoMe** [vim/vim-win32-installer#54]
os：win10 64-bit
vim version：gvim_8.1.0053_x64.zip

my English is not good,I hope I can describe the problem clearly
ok，in my gvim, when I run :term, or run PlugInstall with vim-plug or other commands, I always see the Command Prompt box flash quickly, I have added the vim_installed_path to PATH,and I try to installed with the Self-installing executable,but the problem still exists
Does anyone have the same problem？or is somethings wrong in my settings
(my gvim works well but this problem confused me)

**Comment by chrisbra** [comment]
please explain when this happens.

**Comment by k-takata** [comment]
I don't know about the implementation of vim-plug, but if it uses `system()` or `:!command` to execute external commands, Command Prompt will be shown.
If you add `set guioptions+=!` in your `.vimrc`, `:!command` will be executed in a terminal window.
If the job feature is used, Command Prompt will not be shown.
I don't think it is a problem of this installer package.
Please ask the author of vim-plug or other plugins.
