### ISSUE TITLE
McAfee Virus Alert with gvim_8.1.0126_x86.exe

### ISSUE THREAD

**Issue by psantoro** [vim/vim-win32-installer#56]
At work today (6/29/18), McAfee Enterprise 8.8 (last updated on 6/28/18) detected a virus when I ran the gvim_8.1.0126_x86.exe installer.  To be specific, it quarantined the uninstall-gui.exe claiming it was RDN/Ransom.

I use Windows Defender at home and it did not detect any such issues with the same vim installer.

**Comment by k-takata** [comment]
Please see #53, #55 and related.
