### ISSUE TITLE
Upgrade to Python 3.7

### ISSUE THREAD

**Issue by mohd-akram** [vim/vim-win32-installer#57]

**Comment by k-takata** [comment]
Currently, using Python 3.7 has a problem: vim/vim#3117.
We should fix it before upgrading to 3.7

**Comment by k-takata** [comment]
vim/vim#3117 was fixed by Vim 8.1.201. However there are another issue.
We should wait vim/vim#3162 to be merged.

**Comment by chrisbra** [comment]
anything speaking against upgrading to python 3.7 now? It seems the related vim problems have been fixed.

**Comment by k-takata** [comment]
I think it's okay now.
