### ISSUE TITLE
no x86 builds of nightly?

### ISSUE THREAD

**Issue by jungle-boogie** [vim/vim-win32-installer#58]
Hi @chrisbra,

Thanks for making the nightly builds of vim - really great for you to do so.

Since version https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0127 there haven't been nightly builds of x86. 

Is that deliberate - you're tired of the false positives from virus scanners, or an oversight?

**Comment by k-takata** [comment]
See vim/vim#3144.

**Comment by jungle-boogie** [comment]
Thanks, @k-takata.
