### ISSUE TITLE
Umlaut (ÖÄÜ) can`t be displayed...

### ISSUE THREAD

**Issue by bschley** [vim/vim-win32-installer#59]
Hello,

if I launch the german version of vim for windows I can`t see umlauts in the editor:

![umlaut](https://user-images.githubusercontent.com/3937642/42723007-e7367b40-8755-11e8-80a7-c480ee14e40c.png)

In the middle of the screen, you see 'für' wrong displayed.

**Comment by chrisbra** [comment]
I just tested this locally. In my cmd.exe I have the codepage cp850 and use `:set encoding=utf-8`. For whatever reason I don't currently full understand this works and displays the intro page correctly. However a `vim --clean` in a cp850 codepage cmdline window which starts up as `:set encoding=latin1` displays the wrong characters as in your screen.

So make sure to use the correct `encoding` and codepage.

**Comment by bschley** [comment]
Ok it`s working now... By default without any configuration the encoding is not utf-8.

After I set it to uft-8, all works fine, thx.
