### ISSUE TITLE
ActivePerl issues

### ISSUE THREAD

**Issue by k-takata** [vim/vim-win32-installer#60]
The latest build failed because ActivePerl 5.24.1 is not available anymore:
https://ci.appveyor.com/project/chrisbra/vim-win32-installer/build/job/ak3qaap7yoqldbo5

The latest versions of ActivePerl are 5.26.1 and 5.24.3, but both provides only 64-bit builds.
32-bit versions of 5.26.0 and 5.24.0 are still available, but it might become unavailable in a few months.

We need to decide how to do with this. E.g.:

* Download 32-bit ActivePerl (5.26.0 or 5.24.0) and copy it into our repository.
* Request the AppVeyor support team to install the latest version of 32-bit ActivePerl.
* Stop enabling if_perl.
* Switch our installer to 64-bit version, because users may not get 32-bit ActivePerl near future.

**Comment by chrisbra** [comment]
> Request the AppVeyor support team to install the latest version of 32-bit ActivePerl.

we should do this anyway. 

> Switch our installer to 64-bit version, because users may not get 32-bit ActivePerl near future.

Perhaps it's time to switch to 64bit versions. But that won't help with users who want a 32bit version.

I asked on the ActiveState support forum. Let's wait a couple of days on feedback there and if nothing helps, I think we should temporarily disable if_perl feature.

CC @brammool for his opinion

**Comment by k-takata** [comment]
I found one more option:

* Switch to Strawberry Perl from ActivePerl.

**Comment by chrisbra** [comment]
I got the following information from ActiveState:
Christian,

> 
> Sorry about the delay in responding, but I have now got clearance from the
> product manager to get you a 5.24.1 32-bit version if that's what you really
> need. I wouldn't recommend using any 5.24 version, personally, but if that
> works for you we can find a way to get you a copy.
> 
> 5.24.1 has been unavailable for a while. It was End-of-Life on the release of
> 5.24.3, back in December. After releases are End-of-Life, they get taken down
> from the public pages and moved behind the paywall. That's why you can't find
> 5.24.1.
> 
> In general however, you are correct that 32-bit Windows builds are
> disappearing. As of December 30, 2018, ActiveState will no longer prepare
> Community Edition versions for 32-bit Windows, and we would recommend moving
> to full 64-bit support.
> 
> At the moment, the two final ActivePerl releases that included 32-bit Windows
> versions have yet to expire. However, because of compatibility issues with the
> @INC security fix, we cannot give either of these releases (2403 or 2600) a
> "recommended" tag.
> 
> 5.24.2.2403
> [1]http://downloads.activestate.com/ActivePerl/releases/5.24.2.2403/ActivePerl-5.24.2.2403-MSWin32-x86-64int-403863.exe
> Since there will not be any further 5.24 releases, build 2403 will not go
> End-of-Life until a 5.28 is production ready. This happens when a 5.28.1
> release is available; likely in March of 2019, or so.
> 
> 5.26.0.2600
> [2]http://downloads.activestate.com/ActivePerl/releases/5.26.0.2600/ActivePerl-5.26.0.2600-MSWin32-x86-64int-403866.exe
> The 2600 build will be End-of-Life immediately if a 5.26.2 or a 5.26.3 release
> are issued.
> 
> Best regards,
> 
> Graham Stuart
> Technical Support Engineer
> ActiveState Software

**Comment by k-takata** [comment]
So, 32-bit version of ActivePerl will be disappear sooner or later.
I think we should update 32-bit version to 5.24.2 (and 64-bit version to 5.24.3) for now.
However switching to [Strawberry Perl](http://strawberryperl.com/) might be the best solution?

**Comment by chrisbra** [comment]
> I think we should update 32-bit version to 5.24.2 (and 64-bit version to 5.24.3) for now.

That should work until march 2019, so yes we should go with that for now and test how well Strawberry Perl might work.
