### ISSUE TITLE
uninstall-gui.exe virustotal detection

### ISSUE THREAD

**Issue by PearOfApples** [vim/vim-win32-installer#65]
The uninstall-gui.exe file is being matched on VirusTotal by a non-trivial number of AVs. See https://www.virustotal.com/en/file/6ccd82e1afb291fe95f8b2747d44359093163f5c18f22bd1135eec4b62b5990b/analysis/1533744730/ for more information.

**Comment by k-takata** [comment]
Duplicate of #44, #50, #53, #55, #56
