### ISSUE TITLE
Fatal Python error

### ISSUE THREAD

**Issue by yuwenxianglong** [vim/vim-win32-installer#71]
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00003440 (most recent call first):

**Comment by k-takata** [comment]
Not enough information. Closing.

**Comment by hungpham3112** [comment]
I have the same issue

**Comment by k-takata** [comment]
Please provide enough information.

**Comment by hungpham3112** [comment]
Step to reproduce:

1. Download Vim for Windows 8.2.2824
2. Install python use `scoop` package manager: `scoop install python`
3. Open vim in terminal and see error.

**Comment by k-takata** [comment]
> 1. Download Vim for Windows 8.2.2824

It looks that you are using scoop to install it, and it looks that scoop downloads it from vim.org, not from here.
The official version of Vim 8.2.2824 from vim.org is compiled against Python 3.6, so you have to install Python 3.6, however, it looks that scoop installs Python 3.10 now.
Please install Python 3.6 from python.org. If you don't want to add Python 3.6 to PATH, you can use the 'pythonthreedll' and 'pythonthreehome' options.

**Comment by hungpham3112** [comment]
With blank `vimrc` and run `py3('version')`:

Here is the output:

![image](https://user-images.githubusercontent.com/75968004/152644924-ab72d61b-b1b6-4bcc-bbb7-15fc0b7c8ce0.png)

in vim version 8.2.4286:

![image](https://user-images.githubusercontent.com/75968004/152644994-04643ed0-2583-46b1-8096-66ac0d8a56cf.png)

**Comment by k-takata** [comment]
Vim 8.2.4286 from this repository is compiled against Python 3.10. So, it should work with Python 3.10.

Vim 8.2.2824 from vim.org is compiled against Python 3.6. You must install Python 3.6. But, your first screenshot shows that you are using Python 3.10.

**Comment by hungpham3112** [comment]
> Vim 8.2.4286 from this repository is compiled against Python 3.10. So, it should work with Python 3.10.
> 
> Vim 8.2.2824 from vim.org is compiled against Python 3.6. You must install Python 3.6. But, your first screenshot shows that you are using Python 3.10.

I mean I switch to 8.2.4286 for using python 3.10 but like you see, I can't

**Comment by hungpham3112** [comment]
Ok, I found what happening and the error cause by `coc.nvim`. I removed it and vim run normal. But didn't know exactly why?

**Comment by k-takata** [comment]
It looks that your python 3.10 installation is broken or your python-related settings are broken.

1. Make sure that python 3.10 is correctly installed.
   Where did you install it?
   What does the following command show? `python --version`
2. Check the `PATH` environment variable. Please run the following command from the command prompt.
   `where.exe python310.dll`
3. Check the `PYTHONPATH` and `PYTHONHOME` environment variables.
    Normally, you don't need to set them. If you set them, make sure that python is installed there.
4. Check the `'pythonthreedll'` and `'pythonthreehome'` options.
    Normally, you don't need to set them. If you set them, make sure that python dll exists there and python is installed there.

**Comment by Konfekt** [comment]
In my case, the version of scoop's vim python bind and python version matched, but `python.exe` in `%PATH%` was an outdated version as precedence was given to a directory other than that containing scoop's `python.exe` (that is, it was listed first in `%PATH%`.)
