### ISSUE TITLE
Installed Vim does not add to runtimepath .vim/pack/*/start and opt directories

### ISSUE THREAD

**Issue by boput** [vim/vim-win32-installer#93]
Hello,

After installing Vim using latest 64 bit installer, Vim runtimepath (:set) does not include, nor does loads plugins from .vim\pack\bundle\start or .vim\pack\bundle\opt directories.

Is it intentional? Of course, Vim under linux includes those directories. Also, Vim distributed by Git for Windows does include those directories.

Am I doing something wrong installing on Windows?

**Comment by k-takata** [comment]
It's the default behavior of Windows native version of Vim.
Normally you should use `vimfiles` instead of `.vim`.
If you still want to use `.vim`, you should add it explicitly. E.g. `:set packpath^=~/.vim`

> Also, Vim distributed by Git for Windows does include those directories.

It is a MSYS2 version of Vim. It works like Linux version.

**Comment by boput** [comment]
Thank you.

I prefer to use .vim to keep same directory structure under Linux and Windows.

Thank you for your installers.
