### ISSUE TITLE
Latest releases is deemed unsafe

### ISSUE THREAD

**Issue by Leonkoithara** [vim/vim-win32-installer#97]
The latest release when downloaded chrome browser reports to be unsafe and windows prevents installer from running

**Comment by idbrii** [comment]
@Leonkoithara Which exe did you run? I used gvim_8.1.0527_x64-mui2.exe and get "Windows protected your PC: Windows Defender SmartScreen prevented an unrecognized app from starting."

I don't recall getting that, but I've never used one of the mui2 executables. I don't think the old installer triggered this, but I'm not sure. I assume SmartScreen triggers for any unsigned exe downloaded from the internet.

**Workaround**: If you click "More Info", you get a "Run anyway" button. (This is a bad security practice.)

Also, running the exe inside of gvim_8.1.0527_x64.zip does not trigger the warning (presumably it's the installer's elevated privileges that trigger it).

@chrisbra [it appears this could be solved with signing and time](https://stackoverflow.com/a/51113771/79125) (or signing and money?). Or maybe not requiring elevated privileges?

**Comment by chrisbra** [comment]
I got that message all the time even without the mui exe. You just need to click on advanced and then you can execute the executable (or something similar). That happens only the first time.

Yeah, signing could probably solve that issue, but I have never looked in detailed about it.
